# Make Models

B Steele, Colorado State University, ROSSyndicate — last updated Sep 17, 2026

This notebook trains the production Secchi-depth model: an ensemble of XGBoost models over ten independent HUC8-random CV arrangements built in `03_split_data.ipynb`, evaluated on that notebook's one fixed, never-trained-on holdout.

**Single algorithm, ten seeds.** An earlier version of this pipeline ensembled 5 seeds × 2 algorithms (XGBoost + LightGBM), for 40 models total. A variance decomposition of that ensemble's holdout predictions found the two algorithms agreed very closely with one another (0.998 correlation between their respective 5-seed ensemble means) while different random seeds disagreed with each other substantially more (~0.99 pairwise correlation); seed choice accounted for roughly 65% of the ensemble's internal prediction spread, versus roughly 13% for model architecture. Given that seed, not algorithm, was the dominant source of useful ensemble variability, this pipeline runs a single algorithm (XGBoost) over 10 independent random seeds instead (`601`–`610`) — 10 seeds × 4 folds = 40 models, the same total model count as the original two-algorithm design, for no measurable accuracy cost and a simpler codebase to maintain.

Each ensemble seed runs its own complete feature-selection + tuning + training pipeline, entirely independently, on its own 4-fold split of the shared CV pool. The final production prediction is the average across all 10 seeds × 4 folds.</cell id="4dbf7522">


## Setup

In [1]:
import json
import sys
import time
from pathlib import Path

import numpy as np
import pandas as pd

sys.path.insert(0, str(Path("python").resolve()))
import backward_elim as be
import features
import metrics as M
import model_xgb
import spatial_cv
from tuning import gap_aware_tune

be.register_model("xgboost", model_xgb)

AQUAMATCH_DIR = Path("aquamatch_files")
MODELS_DIR = Path("xg_models") / "v3_production"
MODELS_DIR.mkdir(parents=True, exist_ok=True)

TARGET = "harmonized_value"
MODEL_NAME = "xgboost"
MOD = model_xgb
SEEDS = list(range(601, 611))
N_TRIALS_INITIAL = 25
N_TRIALS_FINAL = 40
ELIM_TOL = 0.005
ELIM_SEED = 47
TUNE_SEED = 47

SITE_COLS = ["elevation_m", "catchment_area_sqkm", "pct_impervious_2006", "pct_urban_2006",
             "pct_forest_2006", "pct_cropland_2006", "pct_wetland_2006", "shore_flag"]
WEATHER_COLS_CURATED = ["precip_mm_prev30", "tmax_degC_prev30"]


def log(seed, msg):
    print(f"[{time.strftime('%H:%M:%S')}][seed{seed}] {msg}", flush=True)

## Load data and build 10 fresh CV-fold arrangements

Reads `03_split_data.ipynb`'s output (the same fixed holdout used everywhere else in this project) and adds 10 new `cvfold_seed{601-610}` columns via `spatial_cv.build_splits` — the holdout itself is rebuilt deterministically from the same `holdout_seed=3`, so it comes back identical to `03`'s; only the CV-pool fold arrangement is new. `04`'s original `cvfold_seed{501-505}` columns are left untouched alongside these.

`features.coarsen_site_features()` reduces `catchment_area_sqkm` (log-scale binned) and the `pct_*_2006` land-cover fractions (rounded to the nearest percentage point) so a heavily-resampled single waterbody's static, per-comid LakeCat values can't act as a de facto waterbody ID for the model to key a memorized SDD value off of. It does not (and isn't meant to) address the separate, already-documented leakage from the handful of waterbodies spanning more than one HUC8 (Lake Powell chief among them) — those stay large and distinct enough to remain identifiable after coarsening by design.

In [2]:
df = pd.read_parquet(AQUAMATCH_DIR / "base_with_splits.parquet")
df = features.add_spectral_indices(df)
df = features.coarsen_site_features(df)
df = spatial_cv.build_splits(df, ensemble_seeds=SEEDS)
print(f"{len(df):,} rows, {df.shape[1]} columns; holdout n={df['is_holdout'].sum():,}")

11,143 rows, 72 columns; holdout n=2,334


## Per-seed pipeline (single algorithm)

Same stages as `04_make_models.ipynb`, minus the cross-algorithm joint elimination step (not applicable with one algorithm) — the single model's own backward-elimination result is the seed's final feature set directly, with no intersection step.

In [3]:
def run_seed_pipeline(seed, df):
    out_dir = MODELS_DIR / f"seed{seed}"
    out_dir.mkdir(parents=True, exist_ok=True)
    t_start = time.time()

    folds = spatial_cv.build_folds(df, seed)
    test = df[df["is_holdout"]].reset_index(drop=True)
    log(seed, f"folds: {[(f.part, len(f.train), len(f.val)) for f in folds]}, holdout n={len(test)}")

    # --- candidate pool + correlation pruning (this seed's own train_val pool) ---
    metadata_cols = {"HUC8", "holdout_part", "is_holdout"} | {f"cvfold_seed{s}" for s in SEEDS}
    extra_cols = set(SITE_COLS) | set(WEATHER_COLS_CURATED) | metadata_cols
    optical_feats = [f for f in features.candidate_feature_list(df) if f not in extra_cols]
    candidates = optical_feats + SITE_COLS + WEATHER_COLS_CURATED

    train_val = pd.concat([f.train for f in folds] + [folds[0].val], ignore_index=True).drop_duplicates(
        subset=["siteSR_id", "date"])
    pruned = features.correlation_prune(train_val, candidates, target=TARGET)
    log(seed, f"candidate pool: {len(candidates)} -> {len(pruned)} after correlation pruning")

    # tuning seed is derived per-ensemble-seed (rather than a single fixed value shared
    # by every seed) so each seed's random search explores a genuinely different draw of
    # hyperparameter combinations - previously every seed reused seed=47 verbatim, so all
    # 10 seeds evaluated the identical set of combinations against their own data instead
    # of diversifying search coverage across the ensemble the way the CV folds and feature
    # selection already do
    seed_tune_seed = TUNE_SEED + seed

    # --- stage 1: initial gap-aware tuning (fixed params for elimination) ---
    log(seed, f"=== initial gap-aware tuning on {len(pruned)}-feature pool ===")
    init_result = gap_aware_tune(MOD, folds, pruned, TARGET, n_trials=N_TRIALS_INITIAL, seed=seed_tune_seed)
    fixed_params = init_result["best_params"]
    log(seed, f"val_rmse={init_result['best_score']:.4f} gap={init_result['best_gap']:.4f}")

    # --- stage 2: backward elimination (single algorithm, no joint step) ---
    log(seed, "=== backward elimination ===")
    elim_result = be.backward_eliminate(MODEL_NAME, folds, TARGET, fixed_params, pruned,
                                        weight_fn=None, tol=ELIM_TOL, seed=ELIM_SEED,
                                        log=lambda m: log(seed, m))
    final_feats = elim_result["final_features"]
    log(seed, f"final ({len(final_feats)}): {final_feats}")

    with open(out_dir / "backward_elim_summary.json", "w") as fh:
        json.dump(dict(starting_candidates=candidates, correlation_pruned=pruned,
                       final_features=final_feats, path=elim_result["path"]), fh, indent=2, default=str)

    # --- stage 3: final gap-aware tuning on the final feature set ---
    log(seed, f"=== final gap-aware tuning on {len(final_feats)}-feature set ===")
    tune_result = gap_aware_tune(MOD, folds, final_feats, TARGET, n_trials=N_TRIALS_FINAL, seed=seed_tune_seed)
    log(seed, f"chosen: val_rmse={tune_result['best_score']:.4f} gap={tune_result['best_gap']:.4f}")
    with open(out_dir / f"final_tune_{MODEL_NAME}.json", "w") as fh:
        json.dump({"model": MODEL_NAME, "features": final_feats, **tune_result}, fh, indent=2, default=str)

    # --- stage 4: final unweighted training + evaluation ---
    params = tune_result["best_params"]
    fold_models = MOD.train_fold_models(folds, final_feats, TARGET, params)
    for i, fm in enumerate(fold_models):
        fm.save_model(str(out_dir / f"{MODEL_NAME}_fold{i+1}.json"))

    cv_preds, cv_ys = [], []
    for f, model in zip(folds, fold_models):
        cv_preds.append(MOD.predict_ensemble([model], f.val[final_feats]))
        cv_ys.append(f.val[TARGET].values)
    cv_metrics = M.all_metrics(np.concatenate(cv_ys), np.concatenate(cv_preds))

    test_pred = MOD.predict_ensemble(fold_models, test[final_feats])
    test_metrics = M.all_metrics(test[TARGET].values, test_pred)
    log(seed, f"FINAL: cv_rmse={cv_metrics['rmse']:.4f} holdout_rmse={test_metrics['rmse']:.4f}")

    summary = {MODEL_NAME: dict(features=final_feats, params=params, cv_metrics=cv_metrics, test_metrics=test_metrics)}
    with open(out_dir / "final_eval_summary.json", "w") as fh:
        json.dump(summary, fh, indent=2, default=str)

    r = test[["siteSR_id", "date", "HUC4", "HUC8"]].copy()
    r["seed"] = seed
    r["model"] = MODEL_NAME
    r["y"] = test[TARGET].values
    r["pred"] = test_pred
    r.to_parquet(out_dir / "holdout_predictions.parquet")

    log(seed, f"SEED {seed} DONE in {time.time()-t_start:.0f}s")
    return summary

In [4]:
all_summaries = {}
for seed in SEEDS:
    all_summaries[seed] = run_seed_pipeline(seed, df)

[22:56:31][seed601] folds: [(1, 6720, 2089), (2, 6535, 2274), (3, 6431, 2378), (4, 6741, 2068)], holdout n=2334


[22:56:31][seed601] candidate pool: 45 -> 34 after correlation pruning


[22:56:31][seed601] === initial gap-aware tuning on 34-feature pool ===


[23:00:36][seed601] val_rmse=1.3229 gap=0.3833


[23:00:36][seed601] === backward elimination ===


[23:01:35][seed601]   [xgboost] step 0: n=34 cv_rmse=1.3257 shadow_floor=0.0003


[23:01:35][seed601]   [xgboost] drop 'precip_mm_prev3' (importance -0.0017 <= shadow floor 0.0003)


[23:02:24][seed601]   [xgboost] step 1: n=33 cv_rmse=1.3306 shadow_floor=0.0003


[23:02:24][seed601]   [xgboost] drop 'tmin_degC_prev30' (importance -0.0009 <= shadow floor 0.0003)


[23:03:22][seed601]   [xgboost] step 2: n=32 cv_rmse=1.3264 shadow_floor=0.0003


[23:03:22][seed601]   [xgboost] drop 'precip_mm_prev30' (importance -0.0013 <= shadow floor 0.0003)


[23:04:12][seed601]   [xgboost] step 3: n=31 cv_rmse=1.3268 shadow_floor=0.0003


[23:04:12][seed601]   [xgboost] stop: worst real feature 'precip_mm_prev7' (0.0004) beats shadow floor (0.0003)


[23:04:12][seed601] final (34): ['atm_corr_LaSRC', 'red_corr7', 'nir_corr7', 'swir1_corr7', 'temp_corr7', 'precip_mm_prev1', 'tmean_degC_prev7', 'srad_Wm2_prev1', 'precip_mm_prev3', 'srad_Wm2_prev7', 'precip_mm_prev7', 'tmax_degC_prev7', 'tmin_degC_prev7', 'tmean_degC_prev30', 'tmin_degC_prev30', 'srad_Wm2_prev30', 'BR', 'BG', 'NR', 'fai', 'NDVI', 'NDSSI', 'NDWI', 'MNDWI', 'elevation_m', 'catchment_area_sqkm', 'pct_impervious_2006', 'pct_urban_2006', 'pct_forest_2006', 'pct_cropland_2006', 'pct_wetland_2006', 'shore_flag', 'precip_mm_prev30', 'tmax_degC_prev30']


[23:04:12][seed601] === final gap-aware tuning on 34-feature set ===


[23:10:56][seed601] chosen: val_rmse=1.3222 gap=0.3635


[23:11:13][seed601] FINAL: cv_rmse=1.3349 holdout_rmse=1.8669


[23:11:13][seed601] SEED 601 DONE in 882s


[23:11:13][seed602] folds: [(1, 6653, 2156), (2, 6630, 2179), (3, 6499, 2310), (4, 6645, 2164)], holdout n=2334


[23:11:13][seed602] candidate pool: 45 -> 34 after correlation pruning


[23:11:13][seed602] === initial gap-aware tuning on 34-feature pool ===


[23:15:02][seed602] val_rmse=1.3424 gap=0.3453


[23:15:02][seed602] === backward elimination ===


[23:15:57][seed602]   [xgboost] step 0: n=34 cv_rmse=1.3507 shadow_floor=0.0004


[23:15:57][seed602]   [xgboost] drop 'tmax_degC_prev7' (importance -0.0030 <= shadow floor 0.0004)


[23:16:49][seed602]   [xgboost] step 1: n=33 cv_rmse=1.3553 shadow_floor=0.0004


[23:16:49][seed602]   [xgboost] drop 'temp_corr7' (importance -0.0015 <= shadow floor 0.0004)


[23:17:39][seed602]   [xgboost] step 2: n=32 cv_rmse=1.3551 shadow_floor=0.0003


[23:17:39][seed602]   [xgboost] drop 'tmin_degC_prev7' (importance -0.0020 <= shadow floor 0.0003)


[23:18:33][seed602]   [xgboost] step 3: n=31 cv_rmse=1.3441 shadow_floor=0.0005


[23:18:33][seed602]   [xgboost] drop 'tmin_degC_prev30' (importance -0.0011 <= shadow floor 0.0005)


[23:19:27][seed602]   [xgboost] step 4: n=30 cv_rmse=1.3495 shadow_floor=0.0004


[23:19:27][seed602]   [xgboost] drop 'swir1_corr7' (importance -0.0023 <= shadow floor 0.0004)


[23:20:17][seed602]   [xgboost] step 5: n=29 cv_rmse=1.3497 shadow_floor=0.0003


[23:20:17][seed602]   [xgboost] drop 'precip_mm_prev30' (importance -0.0006 <= shadow floor 0.0003)


[23:21:11][seed602]   [xgboost] step 6: n=28 cv_rmse=1.3480 shadow_floor=0.0003


[23:21:11][seed602]   [xgboost] drop 'precip_mm_prev3' (importance -0.0001 <= shadow floor 0.0003)


[23:22:08][seed602]   [xgboost] step 7: n=27 cv_rmse=1.3383 shadow_floor=0.0006


[23:22:08][seed602]   [xgboost] drop 'precip_mm_prev7' (importance -0.0003 <= shadow floor 0.0006)


[23:22:56][seed602]   [xgboost] step 8: n=26 cv_rmse=1.3423 shadow_floor=0.0003


[23:22:56][seed602]   [xgboost] drop 'tmean_degC_prev7' (importance -0.0001 <= shadow floor 0.0003)


[23:23:53][seed602]   [xgboost] step 9: n=25 cv_rmse=1.3326 shadow_floor=0.0006


[23:23:53][seed602]   [xgboost] stop: worst real feature 'srad_Wm2_prev7' (0.0009) beats shadow floor (0.0006)


[23:23:53][seed602] final (25): ['atm_corr_LaSRC', 'red_corr7', 'nir_corr7', 'precip_mm_prev1', 'srad_Wm2_prev1', 'srad_Wm2_prev7', 'tmean_degC_prev30', 'srad_Wm2_prev30', 'BR', 'BG', 'NR', 'fai', 'NDVI', 'NDSSI', 'NDWI', 'MNDWI', 'elevation_m', 'catchment_area_sqkm', 'pct_impervious_2006', 'pct_urban_2006', 'pct_forest_2006', 'pct_cropland_2006', 'pct_wetland_2006', 'shore_flag', 'tmax_degC_prev30']


[23:23:53][seed602] === final gap-aware tuning on 25-feature set ===


[23:30:54][seed602] chosen: val_rmse=1.3172 gap=0.3526


[23:31:13][seed602] FINAL: cv_rmse=1.3194 holdout_rmse=1.8567


[23:31:13][seed602] SEED 602 DONE in 1200s


[23:31:13][seed603] folds: [(1, 6562, 2247), (2, 6662, 2147), (3, 6386, 2423), (4, 6817, 1992)], holdout n=2334


[23:31:13][seed603] candidate pool: 45 -> 34 after correlation pruning


[23:31:13][seed603] === initial gap-aware tuning on 34-feature pool ===


[23:35:41][seed603] val_rmse=1.3439 gap=0.4156


[23:35:41][seed603] === backward elimination ===


[23:36:36][seed603]   [xgboost] step 0: n=34 cv_rmse=1.3517 shadow_floor=0.0003


[23:36:36][seed603]   [xgboost] drop 'tmin_degC_prev7' (importance -0.0021 <= shadow floor 0.0003)


[23:37:32][seed603]   [xgboost] step 1: n=33 cv_rmse=1.3494 shadow_floor=0.0003


[23:37:32][seed603]   [xgboost] drop 'tmax_degC_prev7' (importance -0.0020 <= shadow floor 0.0003)


[23:38:22][seed603]   [xgboost] step 2: n=32 cv_rmse=1.3490 shadow_floor=0.0003


[23:38:22][seed603]   [xgboost] drop 'precip_mm_prev3' (importance -0.0021 <= shadow floor 0.0003)


[23:39:18][seed603]   [xgboost] step 3: n=31 cv_rmse=1.3453 shadow_floor=0.0003


[23:39:18][seed603]   [xgboost] drop 'tmean_degC_prev7' (importance -0.0021 <= shadow floor 0.0003)


[23:40:12][seed603]   [xgboost] step 4: n=30 cv_rmse=1.3478 shadow_floor=0.0004


[23:40:12][seed603]   [xgboost] drop 'precip_mm_prev30' (importance -0.0022 <= shadow floor 0.0004)


[23:41:08][seed603]   [xgboost] step 5: n=29 cv_rmse=1.3456 shadow_floor=0.0006


[23:41:08][seed603]   [xgboost] drop 'srad_Wm2_prev7' (importance -0.0011 <= shadow floor 0.0006)


[23:42:06][seed603]   [xgboost] step 6: n=28 cv_rmse=1.3417 shadow_floor=0.0008


[23:42:06][seed603]   [xgboost] drop 'tmin_degC_prev30' (importance 0.0001 <= shadow floor 0.0008)


[23:43:05][seed603]   [xgboost] step 7: n=27 cv_rmse=1.3405 shadow_floor=0.0006


[23:43:05][seed603]   [xgboost] drop 'precip_mm_prev7' (importance 0.0004 <= shadow floor 0.0006)


[23:44:00][seed603]   [xgboost] step 8: n=26 cv_rmse=1.3402 shadow_floor=0.0003


[23:44:00][seed603]   [xgboost] drop 'swir1_corr7' (importance -0.0002 <= shadow floor 0.0003)


[23:44:58][seed603]   [xgboost] step 9: n=25 cv_rmse=1.3407 shadow_floor=0.0004


[23:44:58][seed603]   [xgboost] stop: worst real feature 'srad_Wm2_prev1' (0.0005) beats shadow floor (0.0004)


[23:44:58][seed603] final (26): ['atm_corr_LaSRC', 'red_corr7', 'nir_corr7', 'swir1_corr7', 'temp_corr7', 'precip_mm_prev1', 'srad_Wm2_prev1', 'tmean_degC_prev30', 'srad_Wm2_prev30', 'BR', 'BG', 'NR', 'fai', 'NDVI', 'NDSSI', 'NDWI', 'MNDWI', 'elevation_m', 'catchment_area_sqkm', 'pct_impervious_2006', 'pct_urban_2006', 'pct_forest_2006', 'pct_cropland_2006', 'pct_wetland_2006', 'shore_flag', 'tmax_degC_prev30']


[23:44:58][seed603] === final gap-aware tuning on 26-feature set ===


[23:51:21][seed603] chosen: val_rmse=1.3304 gap=0.4151


[23:51:28][seed603] FINAL: cv_rmse=1.3468 holdout_rmse=1.8683


[23:51:28][seed603] SEED 603 DONE in 1215s


[23:51:28][seed604] folds: [(1, 6253, 2556), (2, 6726, 2083), (3, 6695, 2114), (4, 6753, 2056)], holdout n=2334


[23:51:28][seed604] candidate pool: 45 -> 34 after correlation pruning


[23:51:28][seed604] === initial gap-aware tuning on 34-feature pool ===


[23:55:02][seed604] val_rmse=1.3335 gap=0.4805


[23:55:02][seed604] === backward elimination ===


[23:55:58][seed604]   [xgboost] step 0: n=34 cv_rmse=1.3394 shadow_floor=0.0003


[23:55:58][seed604]   [xgboost] drop 'elevation_m' (importance -0.0091 <= shadow floor 0.0003)


[23:56:57][seed604]   [xgboost] step 1: n=33 cv_rmse=1.3384 shadow_floor=0.0004


[23:56:57][seed604]   [xgboost] drop 'precip_mm_prev3' (importance -0.0034 <= shadow floor 0.0004)


[23:57:50][seed604]   [xgboost] step 2: n=32 cv_rmse=1.3306 shadow_floor=0.0004


[23:57:50][seed604]   [xgboost] drop 'tmin_degC_prev7' (importance -0.0011 <= shadow floor 0.0004)


[23:58:43][seed604]   [xgboost] step 3: n=31 cv_rmse=1.3341 shadow_floor=0.0004


[23:58:43][seed604]   [xgboost] drop 'tmin_degC_prev30' (importance -0.0020 <= shadow floor 0.0004)


[23:59:41][seed604]   [xgboost] step 4: n=30 cv_rmse=1.3275 shadow_floor=0.0006


[23:59:41][seed604]   [xgboost] drop 'precip_mm_prev30' (importance -0.0010 <= shadow floor 0.0006)


[00:00:37][seed604]   [xgboost] step 5: n=29 cv_rmse=1.3336 shadow_floor=0.0004


[00:00:37][seed604]   [xgboost] drop 'precip_mm_prev7' (importance -0.0003 <= shadow floor 0.0004)


[00:01:29][seed604]   [xgboost] step 6: n=28 cv_rmse=1.3284 shadow_floor=0.0002


[00:01:29][seed604]   [xgboost] drop 'tmax_degC_prev7' (importance -0.0010 <= shadow floor 0.0002)


[00:02:19][seed604]   [xgboost] step 7: n=27 cv_rmse=1.3273 shadow_floor=0.0005


[00:02:19][seed604]   [xgboost] drop 'precip_mm_prev1' (importance -0.0007 <= shadow floor 0.0005)


[00:03:09][seed604]   [xgboost] step 8: n=26 cv_rmse=1.3274 shadow_floor=0.0004


[00:03:09][seed604]   [xgboost] drop 'swir1_corr7' (importance -0.0006 <= shadow floor 0.0004)


[00:04:00][seed604]   [xgboost] step 9: n=25 cv_rmse=1.3264 shadow_floor=0.0004


[00:04:00][seed604]   [xgboost] stop: worst real feature 'srad_Wm2_prev1' (0.0016) beats shadow floor (0.0004)


[00:04:00][seed604] final (25): ['atm_corr_LaSRC', 'red_corr7', 'nir_corr7', 'temp_corr7', 'tmean_degC_prev7', 'srad_Wm2_prev1', 'srad_Wm2_prev7', 'tmean_degC_prev30', 'srad_Wm2_prev30', 'BR', 'BG', 'NR', 'fai', 'NDVI', 'NDSSI', 'NDWI', 'MNDWI', 'catchment_area_sqkm', 'pct_impervious_2006', 'pct_urban_2006', 'pct_forest_2006', 'pct_cropland_2006', 'pct_wetland_2006', 'shore_flag', 'tmax_degC_prev30']


[00:04:00][seed604] === final gap-aware tuning on 25-feature set ===


[00:10:10][seed604] chosen: val_rmse=1.3097 gap=0.4225


[00:10:27][seed604] FINAL: cv_rmse=1.3174 holdout_rmse=1.8142


[00:10:27][seed604] SEED 604 DONE in 1139s


[00:10:27][seed605] folds: [(1, 6673, 2136), (2, 6665, 2144), (3, 6667, 2142), (4, 6422, 2387)], holdout n=2334


[00:10:27][seed605] candidate pool: 45 -> 34 after correlation pruning


[00:10:27][seed605] === initial gap-aware tuning on 34-feature pool ===


[00:14:53][seed605] val_rmse=1.3839 gap=0.4876


[00:14:53][seed605] === backward elimination ===


[00:15:47][seed605]   [xgboost] step 0: n=34 cv_rmse=1.4016 shadow_floor=0.0006


[00:15:47][seed605]   [xgboost] drop 'precip_mm_prev30' (importance -0.0009 <= shadow floor 0.0006)


[00:16:47][seed605]   [xgboost] step 1: n=33 cv_rmse=1.3953 shadow_floor=0.0004


[00:16:47][seed605]   [xgboost] drop 'precip_mm_prev3' (importance -0.0012 <= shadow floor 0.0004)


[00:17:40][seed605]   [xgboost] step 2: n=32 cv_rmse=1.3949 shadow_floor=0.0004


[00:17:40][seed605]   [xgboost] drop 'srad_Wm2_prev30' (importance -0.0006 <= shadow floor 0.0004)


[00:18:41][seed605]   [xgboost] step 3: n=31 cv_rmse=1.3929 shadow_floor=0.0004


[00:18:41][seed605]   [xgboost] drop 'swir1_corr7' (importance -0.0004 <= shadow floor 0.0004)


[00:19:45][seed605]   [xgboost] step 4: n=30 cv_rmse=1.3919 shadow_floor=0.0006


[00:19:45][seed605]   [xgboost] drop 'tmin_degC_prev30' (importance -0.0003 <= shadow floor 0.0006)


[00:20:48][seed605]   [xgboost] step 5: n=29 cv_rmse=1.3921 shadow_floor=0.0007


[00:20:48][seed605]   [xgboost] drop 'tmax_degC_prev7' (importance -0.0001 <= shadow floor 0.0007)


[00:21:47][seed605]   [xgboost] step 6: n=28 cv_rmse=1.3945 shadow_floor=0.0003


[00:21:47][seed605]   [xgboost] drop 'precip_mm_prev7' (importance 0.0000 <= shadow floor 0.0003)


[00:22:33][seed605]   [xgboost] step 7: n=27 cv_rmse=1.3945 shadow_floor=0.0003


[00:22:33][seed605]   [xgboost] stop: worst real feature 'tmean_degC_prev7' (0.0008) beats shadow floor (0.0003)


[00:22:33][seed605] final (30): ['atm_corr_LaSRC', 'red_corr7', 'nir_corr7', 'temp_corr7', 'precip_mm_prev1', 'tmean_degC_prev7', 'srad_Wm2_prev1', 'srad_Wm2_prev7', 'precip_mm_prev7', 'tmax_degC_prev7', 'tmin_degC_prev7', 'tmean_degC_prev30', 'tmin_degC_prev30', 'BR', 'BG', 'NR', 'fai', 'NDVI', 'NDSSI', 'NDWI', 'MNDWI', 'elevation_m', 'catchment_area_sqkm', 'pct_impervious_2006', 'pct_urban_2006', 'pct_forest_2006', 'pct_cropland_2006', 'pct_wetland_2006', 'shore_flag', 'tmax_degC_prev30']


[00:22:33][seed605] === final gap-aware tuning on 30-feature set ===


[00:29:57][seed605] chosen: val_rmse=1.3611 gap=0.5455


[00:30:17][seed605] FINAL: cv_rmse=1.3729 holdout_rmse=1.8210


[00:30:17][seed605] SEED 605 DONE in 1190s


[00:30:17][seed606] folds: [(1, 6620, 2189), (2, 6571, 2238), (3, 6665, 2144), (4, 6571, 2238)], holdout n=2334


[00:30:17][seed606] candidate pool: 45 -> 34 after correlation pruning


[00:30:17][seed606] === initial gap-aware tuning on 34-feature pool ===


[00:33:20][seed606] val_rmse=1.3347 gap=0.3560


[00:33:20][seed606] === backward elimination ===


[00:34:09][seed606]   [xgboost] step 0: n=34 cv_rmse=1.3469 shadow_floor=0.0002


[00:34:09][seed606]   [xgboost] drop 'precip_mm_prev3' (importance -0.0013 <= shadow floor 0.0002)


[00:34:49][seed606]   [xgboost] step 1: n=33 cv_rmse=1.3416 shadow_floor=0.0003


[00:34:49][seed606]   [xgboost] drop 'precip_mm_prev30' (importance -0.0015 <= shadow floor 0.0003)


[00:35:31][seed606]   [xgboost] step 2: n=32 cv_rmse=1.3442 shadow_floor=0.0003


[00:35:31][seed606]   [xgboost] drop 'precip_mm_prev7' (importance -0.0008 <= shadow floor 0.0003)


[00:36:17][seed606]   [xgboost] step 3: n=31 cv_rmse=1.3389 shadow_floor=0.0004


[00:36:17][seed606]   [xgboost] drop 'tmax_degC_prev7' (importance -0.0011 <= shadow floor 0.0004)


[00:37:03][seed606]   [xgboost] step 4: n=30 cv_rmse=1.3425 shadow_floor=0.0006


[00:37:03][seed606]   [xgboost] drop 'tmean_degC_prev7' (importance -0.0006 <= shadow floor 0.0006)


[00:37:49][seed606]   [xgboost] step 5: n=29 cv_rmse=1.3401 shadow_floor=0.0003


[00:37:49][seed606]   [xgboost] drop 'tmin_degC_prev7' (importance -0.0012 <= shadow floor 0.0003)


[00:38:38][seed606]   [xgboost] step 6: n=28 cv_rmse=1.3364 shadow_floor=0.0004


[00:38:38][seed606]   [xgboost] drop 'tmin_degC_prev30' (importance 0.0003 <= shadow floor 0.0004)


[00:39:20][seed606]   [xgboost] step 7: n=27 cv_rmse=1.3457 shadow_floor=0.0004


[00:39:20][seed606]   [xgboost] stop: cv_rmse degraded >0.5% from best (1.3364)


[00:39:20][seed606] final (28): ['atm_corr_LaSRC', 'red_corr7', 'nir_corr7', 'swir1_corr7', 'temp_corr7', 'precip_mm_prev1', 'srad_Wm2_prev1', 'srad_Wm2_prev7', 'tmean_degC_prev30', 'tmin_degC_prev30', 'srad_Wm2_prev30', 'BR', 'BG', 'NR', 'fai', 'NDVI', 'NDSSI', 'NDWI', 'MNDWI', 'elevation_m', 'catchment_area_sqkm', 'pct_impervious_2006', 'pct_urban_2006', 'pct_forest_2006', 'pct_cropland_2006', 'pct_wetland_2006', 'shore_flag', 'tmax_degC_prev30']


[00:39:20][seed606] === final gap-aware tuning on 28-feature set ===


[00:44:39][seed606] chosen: val_rmse=1.3295 gap=0.3530


[00:44:53][seed606] FINAL: cv_rmse=1.3338 holdout_rmse=1.8706


[00:44:53][seed606] SEED 606 DONE in 876s


[00:44:53][seed607] folds: [(1, 6715, 2094), (2, 6713, 2096), (3, 6275, 2534), (4, 6724, 2085)], holdout n=2334


[00:44:53][seed607] candidate pool: 45 -> 34 after correlation pruning


[00:44:53][seed607] === initial gap-aware tuning on 34-feature pool ===


[00:48:31][seed607] val_rmse=1.3317 gap=0.4006


[00:48:31][seed607] === backward elimination ===


[00:49:40][seed607]   [xgboost] step 0: n=34 cv_rmse=1.3411 shadow_floor=0.0003


[00:49:40][seed607]   [xgboost] drop 'pct_forest_2006' (importance -0.0021 <= shadow floor 0.0003)


[00:50:37][seed607]   [xgboost] step 1: n=33 cv_rmse=1.3313 shadow_floor=0.0004


[00:50:37][seed607]   [xgboost] drop 'tmin_degC_prev7' (importance -0.0018 <= shadow floor 0.0004)


[00:51:38][seed607]   [xgboost] step 2: n=32 cv_rmse=1.3271 shadow_floor=0.0004


[00:51:38][seed607]   [xgboost] drop 'precip_mm_prev3' (importance -0.0020 <= shadow floor 0.0004)


[00:52:34][seed607]   [xgboost] step 3: n=31 cv_rmse=1.3296 shadow_floor=0.0005


[00:52:34][seed607]   [xgboost] drop 'precip_mm_prev7' (importance -0.0012 <= shadow floor 0.0005)


[00:53:29][seed607]   [xgboost] step 4: n=30 cv_rmse=1.3281 shadow_floor=0.0005


[00:53:29][seed607]   [xgboost] drop 'precip_mm_prev30' (importance -0.0007 <= shadow floor 0.0005)


[00:54:26][seed607]   [xgboost] step 5: n=29 cv_rmse=1.3302 shadow_floor=0.0003


[00:54:26][seed607]   [xgboost] drop 'tmax_degC_prev7' (importance -0.0015 <= shadow floor 0.0003)


[00:55:27][seed607]   [xgboost] step 6: n=28 cv_rmse=1.3295 shadow_floor=0.0005


[00:55:27][seed607]   [xgboost] drop 'tmin_degC_prev30' (importance -0.0006 <= shadow floor 0.0005)


[00:56:26][seed607]   [xgboost] step 7: n=27 cv_rmse=1.3218 shadow_floor=0.0007


[00:56:26][seed607]   [xgboost] drop 'precip_mm_prev1' (importance 0.0006 <= shadow floor 0.0007)


[00:57:18][seed607]   [xgboost] step 8: n=26 cv_rmse=1.3253 shadow_floor=0.0002


[00:57:18][seed607]   [xgboost] stop: worst real feature 'tmean_degC_prev7' (0.0011) beats shadow floor (0.0002)


[00:57:18][seed607] final (27): ['atm_corr_LaSRC', 'red_corr7', 'nir_corr7', 'swir1_corr7', 'temp_corr7', 'precip_mm_prev1', 'tmean_degC_prev7', 'srad_Wm2_prev1', 'srad_Wm2_prev7', 'tmean_degC_prev30', 'srad_Wm2_prev30', 'BR', 'BG', 'NR', 'fai', 'NDVI', 'NDSSI', 'NDWI', 'MNDWI', 'elevation_m', 'catchment_area_sqkm', 'pct_impervious_2006', 'pct_urban_2006', 'pct_cropland_2006', 'pct_wetland_2006', 'shore_flag', 'tmax_degC_prev30']


[00:57:18][seed607] === final gap-aware tuning on 27-feature set ===


[01:03:00][seed607] chosen: val_rmse=1.3197 gap=0.3716


[01:03:16][seed607] FINAL: cv_rmse=1.3402 holdout_rmse=1.9010


[01:03:16][seed607] SEED 607 DONE in 1103s


[01:03:16][seed608] folds: [(1, 6580, 2229), (2, 6623, 2186), (3, 6632, 2177), (4, 6592, 2217)], holdout n=2334


[01:03:16][seed608] candidate pool: 45 -> 34 after correlation pruning


[01:03:16][seed608] === initial gap-aware tuning on 34-feature pool ===


[01:08:10][seed608] val_rmse=1.3502 gap=0.4032


[01:08:10][seed608] === backward elimination ===


[01:09:19][seed608]   [xgboost] step 0: n=34 cv_rmse=1.3535 shadow_floor=0.0007


[01:09:19][seed608]   [xgboost] drop 'precip_mm_prev3' (importance -0.0016 <= shadow floor 0.0007)


[01:10:20][seed608]   [xgboost] step 1: n=33 cv_rmse=1.3584 shadow_floor=0.0003


[01:10:20][seed608]   [xgboost] drop 'precip_mm_prev30' (importance -0.0013 <= shadow floor 0.0003)


[01:11:26][seed608]   [xgboost] step 2: n=32 cv_rmse=1.3479 shadow_floor=0.0005


[01:11:26][seed608]   [xgboost] drop 'tmax_degC_prev7' (importance -0.0007 <= shadow floor 0.0005)


[01:12:31][seed608]   [xgboost] step 3: n=31 cv_rmse=1.3485 shadow_floor=0.0005


[01:12:31][seed608]   [xgboost] drop 'tmin_degC_prev7' (importance -0.0010 <= shadow floor 0.0005)


[01:13:41][seed608]   [xgboost] step 4: n=30 cv_rmse=1.3472 shadow_floor=0.0006


[01:13:41][seed608]   [xgboost] drop 'srad_Wm2_prev7' (importance -0.0010 <= shadow floor 0.0006)


[01:14:43][seed608]   [xgboost] step 5: n=29 cv_rmse=1.3518 shadow_floor=0.0003


[01:14:43][seed608]   [xgboost] drop 'precip_mm_prev7' (importance -0.0003 <= shadow floor 0.0003)


[01:15:46][seed608]   [xgboost] step 6: n=28 cv_rmse=1.3527 shadow_floor=0.0005


[01:15:46][seed608]   [xgboost] drop 'swir1_corr7' (importance -0.0005 <= shadow floor 0.0005)


[01:16:49][seed608]   [xgboost] step 7: n=27 cv_rmse=1.3500 shadow_floor=0.0006


[01:16:49][seed608]   [xgboost] drop 'tmean_degC_prev7' (importance 0.0001 <= shadow floor 0.0006)


[01:17:56][seed608]   [xgboost] step 8: n=26 cv_rmse=1.3521 shadow_floor=0.0003


[01:17:56][seed608]   [xgboost] stop: worst real feature 'precip_mm_prev1' (0.0010) beats shadow floor (0.0003)


[01:17:56][seed608] final (30): ['atm_corr_LaSRC', 'red_corr7', 'nir_corr7', 'swir1_corr7', 'temp_corr7', 'precip_mm_prev1', 'tmean_degC_prev7', 'srad_Wm2_prev1', 'srad_Wm2_prev7', 'precip_mm_prev7', 'tmean_degC_prev30', 'tmin_degC_prev30', 'srad_Wm2_prev30', 'BR', 'BG', 'NR', 'fai', 'NDVI', 'NDSSI', 'NDWI', 'MNDWI', 'elevation_m', 'catchment_area_sqkm', 'pct_impervious_2006', 'pct_urban_2006', 'pct_forest_2006', 'pct_cropland_2006', 'pct_wetland_2006', 'shore_flag', 'tmax_degC_prev30']


[01:17:56][seed608] === final gap-aware tuning on 30-feature set ===


[01:26:41][seed608] chosen: val_rmse=1.3401 gap=0.4316


[01:27:02][seed608] FINAL: cv_rmse=1.3525 holdout_rmse=1.8515


[01:27:02][seed608] SEED 608 DONE in 1426s


[01:27:02][seed609] folds: [(1, 6590, 2219), (2, 6642, 2167), (3, 6575, 2234), (4, 6620, 2189)], holdout n=2334


[01:27:02][seed609] candidate pool: 45 -> 34 after correlation pruning


[01:27:02][seed609] === initial gap-aware tuning on 34-feature pool ===


[01:30:21][seed609] val_rmse=1.3188 gap=0.3576


[01:30:21][seed609] === backward elimination ===


[01:31:12][seed609]   [xgboost] step 0: n=34 cv_rmse=1.3286 shadow_floor=0.0004


[01:31:12][seed609]   [xgboost] drop 'elevation_m' (importance -0.0070 <= shadow floor 0.0004)


[01:31:58][seed609]   [xgboost] step 1: n=33 cv_rmse=1.3143 shadow_floor=0.0004


[01:31:58][seed609]   [xgboost] drop 'tmax_degC_prev7' (importance -0.0015 <= shadow floor 0.0004)


[01:32:45][seed609]   [xgboost] step 2: n=32 cv_rmse=1.3147 shadow_floor=0.0004


[01:32:45][seed609]   [xgboost] drop 'precip_mm_prev3' (importance -0.0011 <= shadow floor 0.0004)


[01:33:39][seed609]   [xgboost] step 3: n=31 cv_rmse=1.3127 shadow_floor=0.0002


[01:33:39][seed609]   [xgboost] drop 'precip_mm_prev7' (importance -0.0006 <= shadow floor 0.0002)


[01:34:33][seed609]   [xgboost] step 4: n=30 cv_rmse=1.3097 shadow_floor=0.0004


[01:34:33][seed609]   [xgboost] drop 'precip_mm_prev30' (importance -0.0009 <= shadow floor 0.0004)


[01:35:27][seed609]   [xgboost] step 5: n=29 cv_rmse=1.3087 shadow_floor=0.0005


[01:35:27][seed609]   [xgboost] drop 'swir1_corr7' (importance 0.0001 <= shadow floor 0.0005)


[01:36:25][seed609]   [xgboost] step 6: n=28 cv_rmse=1.3038 shadow_floor=0.0003


[01:36:25][seed609]   [xgboost] drop 'tmin_degC_prev7' (importance -0.0011 <= shadow floor 0.0003)


[01:37:22][seed609]   [xgboost] step 7: n=27 cv_rmse=1.3047 shadow_floor=0.0004


[01:37:22][seed609]   [xgboost] stop: worst real feature 'srad_Wm2_prev7' (0.0011) beats shadow floor (0.0004)


[01:37:22][seed609] final (28): ['atm_corr_LaSRC', 'red_corr7', 'nir_corr7', 'temp_corr7', 'precip_mm_prev1', 'tmean_degC_prev7', 'srad_Wm2_prev1', 'srad_Wm2_prev7', 'tmin_degC_prev7', 'tmean_degC_prev30', 'tmin_degC_prev30', 'srad_Wm2_prev30', 'BR', 'BG', 'NR', 'fai', 'NDVI', 'NDSSI', 'NDWI', 'MNDWI', 'catchment_area_sqkm', 'pct_impervious_2006', 'pct_urban_2006', 'pct_forest_2006', 'pct_cropland_2006', 'pct_wetland_2006', 'shore_flag', 'tmax_degC_prev30']


[01:37:22][seed609] === final gap-aware tuning on 28-feature set ===


[01:42:47][seed609] chosen: val_rmse=1.2936 gap=0.3592


[01:43:05][seed609] FINAL: cv_rmse=1.3064 holdout_rmse=1.8268


[01:43:05][seed609] SEED 609 DONE in 963s


[01:43:05][seed610] folds: [(1, 6405, 2404), (2, 6718, 2091), (3, 6718, 2091), (4, 6586, 2223)], holdout n=2334


[01:43:05][seed610] candidate pool: 45 -> 34 after correlation pruning


[01:43:05][seed610] === initial gap-aware tuning on 34-feature pool ===


[01:46:54][seed610] val_rmse=1.3505 gap=0.4290


[01:46:54][seed610] === backward elimination ===


[01:48:06][seed610]   [xgboost] step 0: n=34 cv_rmse=1.3552 shadow_floor=0.0005


[01:48:06][seed610]   [xgboost] drop 'precip_mm_prev30' (importance -0.0008 <= shadow floor 0.0005)


[01:49:12][seed610]   [xgboost] step 1: n=33 cv_rmse=1.3556 shadow_floor=0.0004


[01:49:12][seed610]   [xgboost] drop 'precip_mm_prev3' (importance 0.0003 <= shadow floor 0.0004)


[01:50:13][seed610]   [xgboost] step 2: n=32 cv_rmse=1.3540 shadow_floor=0.0006


[01:50:13][seed610]   [xgboost] stop: worst real feature 'tmax_degC_prev7' (0.0010) beats shadow floor (0.0006)


[01:50:13][seed610] final (32): ['atm_corr_LaSRC', 'red_corr7', 'nir_corr7', 'swir1_corr7', 'temp_corr7', 'precip_mm_prev1', 'tmean_degC_prev7', 'srad_Wm2_prev1', 'srad_Wm2_prev7', 'precip_mm_prev7', 'tmax_degC_prev7', 'tmin_degC_prev7', 'tmean_degC_prev30', 'tmin_degC_prev30', 'srad_Wm2_prev30', 'BR', 'BG', 'NR', 'fai', 'NDVI', 'NDSSI', 'NDWI', 'MNDWI', 'elevation_m', 'catchment_area_sqkm', 'pct_impervious_2006', 'pct_urban_2006', 'pct_forest_2006', 'pct_cropland_2006', 'pct_wetland_2006', 'shore_flag', 'tmax_degC_prev30']


[01:50:13][seed610] === final gap-aware tuning on 32-feature set ===


[01:56:32][seed610] chosen: val_rmse=1.3443 gap=0.4503


[01:56:50][seed610] FINAL: cv_rmse=1.3499 holdout_rmse=1.8798


[01:56:50][seed610] SEED 610 DONE in 825s


## Per-seed summary

In [5]:
rows = []
for seed, summary in all_summaries.items():
    s = summary[MODEL_NAME]
    rows.append(dict(seed=seed, n_features=len(s["features"]), cv_rmse=s["cv_metrics"]["rmse"],
                     holdout_rmse=s["test_metrics"]["rmse"], holdout_bias=s["test_metrics"]["bias"]))
pd.DataFrame(rows).sort_values("seed")

,seed,n_features,cv_rmse,holdout_rmse,holdout_bias
0,601,34,1.334909,1.866912,0.261629
1,602,25,1.319448,1.856715,0.276971
2,603,26,1.346800,1.868308,0.331983
3,604,25,1.317395,1.814210,0.127317
4,605,30,1.372884,1.821035,0.233165
5,606,28,1.333762,1.870621,0.270614
6,607,27,1.340205,1.900975,0.265158
7,608,30,1.352509,1.851494,0.284390
8,609,28,1.306364,1.826814,0.163618
9,610,32,1.349910,1.879784,0.300789


## Assemble the 10-seed ensemble

40 models (10 seeds x 4 folds). Full evaluation (HUC8 breakdown, seed-vs-seed spread, SHAP) happens in `05_evaluate_ensemble.ipynb`; this is a quick sanity check on the assembled holdout metrics before moving on.

In [6]:
rows = []
for seed in SEEDS:
    rows.append(pd.read_parquet(MODELS_DIR / f"seed{seed}" / "holdout_predictions.parquet"))
all_preds = pd.concat(rows, ignore_index=True)

ensemble_pred = all_preds.groupby(["siteSR_id", "date"]).agg(y=("y", "first"), pred=("pred", "mean")).reset_index()
ensemble_metrics = M.all_metrics(ensemble_pred["y"], ensemble_pred["pred"])
print(f"production ensemble (10 seeds x xgboost, 40 models): {ensemble_metrics}")

production ensemble (10 seeds x xgboost, 40 models): {'rmse': 1.8466498435492145, 'mae': 1.3469278292199338, 'mape': 0.6974475150947105, 'bias': 0.21648619859614288, 'p_bias': 5.404338563371457, 'smape': 0.38109833864420484, 'r2': 0.5075473903548398, 'n': 2133}


## Summary

The production model is a 40-member ensemble — 10 independent HUC8-random CV arrangements x 4 folds each — trained unweighted, with gap-aware hyperparameter selection at every tuning stage and per-seed feature sets chosen by correlation pruning followed by shadow-decoy backward elimination. Every member is evaluated on one fixed HUC8-random holdout that no model ever trains on. Artifacts (fold models, per-seed feature/hyperparameter configs, holdout predictions) are saved under `xg_models/v3_production/seed{601–610}/`. See `05_evaluate_ensemble.ipynb` for the full evaluation (HUC8 breakdown, seed-vs-seed spread, SHAP).