{
  "hash": "c0000880314e4b8dfaeaa81c8e3a3076",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Northern Water / Cache la Poudre Out-of-Sample Application\"\nauthor: \"B Steele, Colorado State University, ROSSyndicate\"\ndate: \"last updated Sep 19, 2026\"\noutput:\n  html_document:\n    fig_retina: 1\n---\n\n**Out-of-sample application · R · run from the repository root**\n\n- **Purpose:** Apply the production ensemble to Northern Water / Cache la Poudre remote sensing data under the same siteSR QA and applicability checks as the regional application, and score it against the NW/CLP Secchi record.\n- **Inputs:** `../NW-CLP-RS/` collated siteSR feather; NW harmonized Secchi CSV (`SDD_PATH`); lakeSR handoff CSV and Landsat scene metadata (`aquamatch_files/downloads/`); `aquamatch_files/base_with_splits.parquet`; `regional_clarity/xg_models/v3_production/` (fold models, `ensemble_mean_abs_shap.csv`); elevation, LakeCat and gridMET (cached).\n- **Outputs:** `NW_CLP_application/output/`: predicted-vs-observed, evaluation, and filter-step CSVs, `NW_CLP_full_predictions.feather` (with per-image pass/fail flags), cached fetches.\n- **Depends on:** [04 · Make models](../regional_clarity/04_make_models.ipynb), [05 · Evaluate ensemble](../regional_clarity/05_evaluate_ensemble.ipynb) (SHAP weights for the AOA); mirrors the checks in [07 · Regional application](../regional_clarity/07_regional_application.Rmd)\n\nThis notebook applies the current production model — `04_make_models.ipynb`'s 10-seed, XGBoost-only ensemble (40 fold models) — to out-of-sample remote sensing data from the Northern Water / Cache la Poudre (NW/CLP) service area, a separate project (`../NW-CLP-RS`) not used anywhere in this project's training or holdout data, and reports performance against the observed Secchi depth record available for that area.\n\nThe application is held to the same standard as the regional application in `07_regional_application.Rmd`. Scenes pass the same siteSR QA used to build the training data (pixel QA, surface-temperature bounds, scene cloud cover, and band RANSAC). An estimate is evaluated only if it also passes every one of `07`'s applicability checks: training mission, seasonal window, complete inputs, training range, area of applicability, and the plausibility floor. The model is therefore scored only where it is being applied within its domain. For comparison, performance is also reported with the applicability checks ignored.\n\nThis replaces `4_apply_to_NW.R`, which applied an early, now-superseded 4-fold model using only spectral-ratio features and a stale copy of the band-correction coefficients. The current model needs more than spectral bands — its unanimous feature core includes site characteristics (elevation, LakeCat catchment land cover) and antecedent weather (gridMET) — so this notebook is substantially larger in scope than the script it replaces: it fetches those inputs fresh for the NW/CLP site set (neither exists for these sites anywhere in this project), the same way `02b_pull_site_characteristics.Rmd` and `02c_pull_weather_summaries.Rmd` do for the regional training set.\n\n**Why XGBoost in R:** XGBoost's JSON model format is directly loadable in R (`xgb.load()`) with no conversion step; this was verified directly (predictions from an R-loaded model matched Python's own predictions to \\~0.003 m) before starting this notebook.\n\n**Known, deliberate gaps between this application and training** (see the corresponding questions this project's user resolved before this notebook was written):\n\n- **`shore_flag` is computed fresh from real waterbody geometry, not copied from AquaMatch's QA join.** This file's own `comid` turned out NOT to be a usable NHDPlusV2 identifier (confirmed against the LakeCat API directly — more below), so every site is re-matched to its NHDPlusV2 waterbody polygon via `nhdplusTools::get_waterbodies()`; `shore_flag` is then derived from actual distances to that polygon (`1` if the site point falls outside the matched polygon, or within 230 m of its boundary — the same 200 m site buffer + 30 m optical pixel threshold used to define the training-time flag; `0` otherwise), rather than reused from a different QA process.\n- **Antecedent weather is anchored on the image date alone**, not `max(image_date, field_date)` as in training. At real deployment there is no known field-sample date to anchor on — this matches how the model would actually be used to score an arbitrary satellite pass.\n- **Site characteristics are joined on a freshly-resolved NHDPlusV2 comid, not this file's own `comid`/`permanent_identifier` columns.** Both were tested directly against the LakeCat API and neither matched (0/40 sites resolved in a spot check) — this file was very likely built against NHDPlusHR, a different identifier system than NHDPlusV2 (what StreamCat/LakeCat, and this project's own training pipeline, are built on). `nhdplusTools::get_waterbodies()` resolves a real NHDPlusV2 comid per site by spatial match instead.\n\n\n\n## Setup\n\nLoad packages and set the inputs: the NW/CLP remote sensing file, the NW\nSecchi record, the lakeSR handoff coefficients, and the production model\ndirectory with its 10 ensemble seeds. Also set the output and cache\ndirectory, the cache-refresh switch, and the ROSSyndicate color palette\nused in the figures.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(arrow)\nlibrary(tidyverse)\nlibrary(sf)\nlibrary(elevatr)\nlibrary(nhdplusTools)\nlibrary(StreamCatTools)\nlibrary(parallel)\nlibrary(climateR)\nlibrary(data.table)\nlibrary(xgboost)\nlibrary(jsonlite)\nlibrary(Metrics)\nlibrary(RANN)\n\nlog <- function(...) cat(sprintf(\"[%s] \", format(Sys.time(), \"%H:%M:%S\")), sprintf(...), \"\\n\")\n\nNW_RS_PATH <- \"../NW-CLP-RS/b_site_RS_data_acquisition/out/2025-04-01/NW_Poudre_Historical_collated_DSWE1_site_meta_v2025-04-01.feather\"\nSDD_PATH <- \"data/waterQuality/harmonized/Secchi_data_NW_harmonized_2024-01-01.csv\"\nHANDOFFS_PATH <- \"regional_clarity/aquamatch_files/downloads/lakeSR_collated_handoffs_GEEv2025-02-12_QAv2025-06-04.csv\"\nSCENE_META_DIR <- \"regional_clarity/aquamatch_files/downloads\"\nTRAINING_PATH <- \"regional_clarity/aquamatch_files/base_with_splits.parquet\"\nMODEL_DIR <- \"regional_clarity/xg_models/v3_production\"\nENSEMBLE_SEEDS <- 601:610\n\nOUT_DIR <- \"NW_CLP_application/output\"\ndir.create(OUT_DIR, showWarnings = FALSE)\n\n# the elevation/waterbody/LakeCat and gridMET fetches below are each cached to\n# OUT_DIR as a feather file; re-running the notebook loads from cache instead\n# of re-fetching. Set to TRUE to force a fresh fetch (e.g. after the RS input\n# file's site set changes).\nFORCE_REFRESH_CACHE <- FALSE\n\nROSS_LT_PAL <- c(\"#002EA3\", \"#E70870\", \"#256BF5\", \"#745CFB\", \"#1E4D2B\", \"#56104E\", \"#888888\")\n```\n:::\n\n\n## Read and QA-filter the RS data\n\nThe siteSR QA applied to the regional data in `01_filter_AquaMatch_Data.Rmd` is applied here too, so the model only sees scenes that would have passed QA in the training data:\n\n- **Pixel QA:** `pCount_dswe1/pCount_dswe_gt0 > 0.5`, `pCount_dswe1 > 8`, `prop_clouds == 0`.\n- **Surface temperature:** median surface temperature between 0 °C and 40 °C (273.15–313.15 K), the bounds behind AquaMatch's `flag_temp_min`/`flag_temp_max`. This file does not carry those flags, so the bounds are applied directly.\n- **Scene cloud cover < 20%:** this file's own `CLOUD_COVER` column is empty, so cloud cover is taken from AquaMatch's scene-level metadata (the same files `01` uses), matched on the Landsat scene identifier (mission, path/row, and date). A scene missing from that metadata cannot be confirmed as clear and is dropped, which matches the regional treatment.\n\nBand RANSAC, the last step of the regional siteSR QA, follows the band harmonization below. Each step's row and site counts are logged in `qa_log`.\n\nThe image date isn't in its own column in this file version — it's embedded in `system:index` (e.g. `\"1_1_LT04_033032_19830119_3\"` or `\"2_LE07_033032_19990710_1\"`, an 8-digit `YYYYMMDD` token second from the end regardless of how many leading tokens the mission/path-row segment uses).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nNW_RS_raw <- read_feather(NW_RS_PATH)\nlog(\"raw: %s rows, %s unique sites (r_id)\", nrow(NW_RS_raw), n_distinct(NW_RS_raw$r_id))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[14:28:41]  raw: 321637 rows, 485 unique sites (r_id) \n```\n\n\n:::\n\n```{.r .cell-code}\nNW_RS <- NW_RS_raw %>%\n  mutate(across(c(pCount_dswe1, pCount_dswe_gt0, prop_clouds,\n                  med_Red, med_Blue, med_Green, med_Nir, med_Swir1, med_Swir2, med_SurfaceTemp),\n                as.numeric)) %>%\n  filter(pCount_dswe1 / pCount_dswe_gt0 > 0.5, pCount_dswe1 > 8, prop_clouds == 0)\n\nlog_qa <- function(qa_log, df, step) {\n  bind_rows(qa_log, tibble(step = step, n_rows = nrow(df), n_sites = n_distinct(df$r_id)))\n}\nqa_log <- tibble(step = \"Raw NW/CLP siteSR rows\", n_rows = nrow(NW_RS_raw), n_sites = n_distinct(NW_RS_raw$r_id))\nqa_log <- log_qa(qa_log, NW_RS, \"Pixel QA (DSWE share/count, no clouds in buffer)\")\n\nNW_RS <- NW_RS %>% filter(between(med_SurfaceTemp, 273.15, 313.15))\nqa_log <- log_qa(qa_log, NW_RS, \"Median surface temperature 0-40 °C\")\n\n# scene-level cloud cover from AquaMatch's scene metadata, keyed on the\n# mission_pathrow_date core of the GEE scene id (the leading merge-index\n# tokens differ between the two collections)\nSCENE_ID_PATTERN <- \"L[CTE]0\\\\d_\\\\d{6}_\\\\d{8}\"\nclear_scenes <- list.files(SCENE_META_DIR, pattern = \"sceneMetadata_Landsat(457|89)\\\\.csv$\", full.names = TRUE) %>%\n  map(~ read_csv(.x, show_col_types = FALSE, col_select = c(sat_id, CLOUD_COVER))) %>%\n  bind_rows() %>%\n  filter(CLOUD_COVER < 20) %>%\n  mutate(scene_id = str_extract(sat_id, SCENE_ID_PATTERN)) %>%\n  pull(scene_id) %>%\n  unique()\n\nNW_RS <- NW_RS %>%\n  mutate(scene_id = str_extract(`system:index`, SCENE_ID_PATTERN)) %>%\n  filter(scene_id %in% clear_scenes)\nqa_log <- log_qa(qa_log, NW_RS, \"Scene cloud cover < 20%\")\n\n# date: second-to-last \"_\"-delimited token of system:index, regardless of\n# leading-token count (LANDSAT_4/5 carry one extra leading token vs. 7/8/9)\nindex_parts <- str_split(NW_RS$`system:index`, \"_\")\nNW_RS <- NW_RS %>%\n  mutate(date = as.Date(map_chr(index_parts, ~ .x[length(.x) - 1]), format = \"%Y%m%d\"),\n         lat = Latitude, lon = Longitude)\nstopifnot(\"date parsing failed for some rows\" = sum(is.na(NW_RS$date)) == 0)\n\nlog(\"QA-filtered: %s rows, %s unique sites, date range %s to %s\",\n    nrow(NW_RS), n_distinct(NW_RS$r_id), min(NW_RS$date), max(NW_RS$date))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[14:28:44]  QA-filtered: 133275 rows, 397 unique sites, date range 1984-04-10 to 2024-12-21 \n```\n\n\n:::\n:::\n\n\n## Cross-sensor band harmonization\n\nSame Gardner coefficients (referenced to Landsat 7) this project's own production pipeline uses (`aquamatch_files/downloads/lakeSR_collated_handoffs_...csv`), not `4_apply_to_NW.R`'s stale standalone copy — this file's `mission` values (`\"LANDSAT_4\"`, etc.) are the full GEE-style names rather than this project's `\"LT04\"`-style codes, so the sensor-family mapping is re-derived here rather than reused directly.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nam_corr_LS7 <- read_csv(HANDOFFS_PATH, show_col_types = FALSE) %>%\n  filter(correction == \"Gardner\", dswe == \"DSWE1\", sat_to == \"LS7\") %>%\n  pivot_longer(cols = c(intercept, B1, B2, min_in_val, max_in_val),\n               names_to = \"int_coef\", values_to = \"value\") %>%\n  mutate(new_column = paste(band, int_coef, sep = \"_\")) %>%\n  select(-c(band, int_coef, slope, method)) %>%\n  pivot_wider(names_from = new_column, values_from = value)\n\nNW_RS_corr <- NW_RS %>%\n  mutate(sat_corr = case_when(mission %in% c(\"LANDSAT_4\", \"LANDSAT_5\") ~ \"LS5\",\n                              mission == \"LANDSAT_7\" ~ \"LS7\",\n                              mission %in% c(\"LANDSAT_8\", \"LANDSAT_9\") ~ \"LS8\",\n                              TRUE ~ NA_character_),\n         atm_corr_LaSRC = as.numeric(mission %in% c(\"LANDSAT_8\", \"LANDSAT_9\"))) %>%\n  left_join(am_corr_LS7, by = \"sat_corr\")\n\nNW_RS_corr <- NW_RS_corr %>%\n  mutate(red_corr7 = med_Red_intercept + med_Red_B1 * med_Red + med_Red_B2 * med_Red^2,\n         green_corr7 = med_Green_intercept + med_Green_B1 * med_Green + med_Green_B2 * med_Green^2,\n         blue_corr7 = med_Blue_intercept + med_Blue_B1 * med_Blue + med_Blue_B2 * med_Blue^2,\n         nir_corr7 = med_Nir_intercept + med_Nir_B1 * med_Nir + med_Nir_B2 * med_Nir^2,\n         swir1_corr7 = med_Swir1_intercept + med_Swir1_B1 * med_Swir1 + med_Swir1_B2 * med_Swir1^2,\n         swir2_corr7 = med_Swir2_intercept + med_Swir2_B1 * med_Swir2 + med_Swir2_B2 * med_Swir2^2,\n         temp_corr7 = med_SurfaceTemp_intercept + med_SurfaceTemp_B1 * med_SurfaceTemp +\n           med_SurfaceTemp_B2 * med_SurfaceTemp^2) %>%\n  mutate(red_corr7 = if_else(sat_corr == \"LS7\", med_Red, red_corr7),\n         green_corr7 = if_else(sat_corr == \"LS7\", med_Green, green_corr7),\n         blue_corr7 = if_else(sat_corr == \"LS7\", med_Blue, blue_corr7),\n         nir_corr7 = if_else(sat_corr == \"LS7\", med_Nir, nir_corr7),\n         swir1_corr7 = if_else(sat_corr == \"LS7\", med_Swir1, swir1_corr7),\n         swir2_corr7 = if_else(sat_corr == \"LS7\", med_Swir2, swir2_corr7),\n         temp_corr7 = if_else(sat_corr == \"LS7\", med_SurfaceTemp, temp_corr7)) %>%\n  select(-all_of(names(am_corr_LS7)[names(am_corr_LS7) != \"sat_corr\"]))\n```\n:::\n\n\n## Band RANSAC\n\nThis is the per-site multiband RANSAC filter from `01_filter_AquaMatch_Data.Rmd`, run on the harmonized bands. For each site, it repeatedly fits a linear trend through time to each of the seven harmonized channels using random subsamples of 10 scenes. Each band's residuals are standardized by that band's MAD, and the bands are combined into one score per scene. A scene is kept if at least half of the iterations call it an inlier. A scene is also kept if every one of its band values falls within the range spanned by the site's inliers. Sites with 10 or fewer scenes, which RANSAC cannot evaluate (`NA`), are kept, as in `01`. The function and its parameters are identical to `01` (only the band column names differ: `*_corr7` here, `*_corr_7` there). The flags are cached to `OUT_DIR`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# identical to ransac_site_multiband() / ols_fit() in 01_filter_AquaMatch_Data.Rmd\nols_fit <- function(t, y) {\n  ok <- is.finite(t) & is.finite(y)\n  if (sum(ok) < 2 || length(unique(t[ok])) < 2) {\n    return(c(intercept = NA_real_, slope = NA_real_))\n  }\n  tt <- t[ok]; yy <- y[ok]\n  tm <- mean(tt); ym <- mean(yy)\n  slope <- sum((tt - tm) * (yy - ym)) / sum((tt - tm)^2)\n  c(intercept = ym - slope * tm, slope = slope)\n}\n\nransac_site_multiband <- function(date, band_mat,\n                                  n_iter = 150,\n                                  n_mad = 2.5,\n                                  min_diff = c(red_corr7 = 0.01, green_corr7 = 0.01,\n                                               blue_corr7 = 0.01, nir_corr7 = 0.01,\n                                               swir1_corr7 = 0.01, swir2_corr7 = 0.01,\n                                               temp_corr7 = 1),\n                                  min_sample = 10,\n                                  vote_frac_cutoff = 0.5) {\n  n <- nrow(band_mat)\n  nb <- ncol(band_mat)\n  if (n < min_sample + 1) return(rep(NA, n))\n\n  min_diff_b <- min_diff[colnames(band_mat)]\n  t <- as.numeric(date)\n\n  band_scale <- vapply(seq_len(nb), function(b) {\n    y <- band_mat[, b]\n    cf <- ols_fit(t, y)\n    resid <- y - (cf[\"intercept\"] + cf[\"slope\"] * t)\n    s <- mad(resid, na.rm = TRUE)\n    if (is.na(s) || s == 0) s <- sd(resid, na.rm = TRUE)\n    s\n  }, numeric(1))\n\n  inlier_votes <- rep(0L, n)\n  n_valid_iter <- 0L\n\n  for (i in 1:n_iter) {\n    idx <- sample(n, min_sample)\n    if (length(unique(t[idx])) < 2) next\n\n    z <- matrix(NA_real_, nrow = n, ncol = nb)\n    for (b in seq_len(nb)) {\n      y <- band_mat[, b]\n      if (length(unique(y[idx])) < 2 || is.na(band_scale[b]) || band_scale[b] == 0) next\n      cf <- ols_fit(t[idx], y[idx])\n      if (anyNA(cf)) next\n      resid <- y - (cf[\"intercept\"] + cf[\"slope\"] * t)\n      z[, b] <- abs(resid) / band_scale[b]\n      z[abs(resid) < min_diff_b[b], b] <- 0\n    }\n\n    combined_z <- rowMeans(z, na.rm = TRUE)\n    inliers <- !is.na(combined_z) & combined_z < n_mad\n    inlier_votes <- inlier_votes + as.integer(inliers)\n    n_valid_iter <- n_valid_iter + 1L\n  }\n\n  if (n_valid_iter == 0) return(rep(NA, n))\n\n  best_inliers <- (inlier_votes / n_valid_iter) >= vote_frac_cutoff\n\n  if (any(best_inliers)) {\n    in_range <- vapply(seq_len(nb), function(b) {\n      y <- band_mat[, b]\n      accepted <- y[best_inliers]\n      if (length(accepted) == 0 || all(is.na(accepted))) return(rep(TRUE, n))\n      rng <- range(accepted, na.rm = TRUE)\n      y >= rng[1] & y <= rng[2]\n    }, logical(n))\n    best_inliers <- best_inliers | apply(in_range, 1, all)\n  }\n\n  best_inliers\n}\n\nransac_band_cols <- c(\"red_corr7\", \"green_corr7\", \"blue_corr7\",\n                      \"nir_corr7\", \"swir1_corr7\", \"swir2_corr7\", \"temp_corr7\")\nransac_cache <- file.path(OUT_DIR, \"NW_CLP_band_ransac_flags.feather\")\nstopifnot(\"system:index is not unique per row\" = !anyDuplicated(NW_RS_corr$`system:index`))\n\nif (!FORCE_REFRESH_CACHE && file.exists(ransac_cache)) {\n  ransac_flags <- read_feather(ransac_cache)\n} else {\n  # sequential rather than mclapply: Positron disallows forking the R session\n  set.seed(47)\n  t0 <- Sys.time()\n  ransac_flags <- NW_RS_corr %>%\n    arrange(r_id, date) %>%\n    group_by(r_id) %>%\n    group_split() %>%\n    map(\\(site_df) site_df %>%\n          mutate(is_band_inlier = ransac_site_multiband(date, as.matrix(pick(all_of(ransac_band_cols))))) %>%\n          select(`system:index`, is_band_inlier)) %>%\n    bind_rows()\n  log(\"band RANSAC took %.1f min\", as.numeric(difftime(Sys.time(), t0, units = \"mins\")))\n  write_feather(ransac_flags, ransac_cache)\n}\n\nNW_RS_corr <- NW_RS_corr %>%\n  left_join(ransac_flags, by = \"system:index\") %>%\n  filter(is_band_inlier | is.na(is_band_inlier)) %>%\n  select(-is_band_inlier)\nqa_log <- log_qa(qa_log, NW_RS_corr, \"Band RANSAC\")\nqa_log\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 3\n  step                                             n_rows n_sites\n  <chr>                                             <int>   <int>\n1 Raw NW/CLP siteSR rows                           321637     485\n2 Pixel QA (DSWE share/count, no clouds in buffer) 188031     408\n3 Median surface temperature 0-40 °C               183983     406\n4 Scene cloud cover < 20%                          133275     397\n5 Band RANSAC                                      128078     397\n```\n\n\n:::\n:::\n\n\n## Spectral indices\n\nR port of `python/features.py`'s `add_spectral_indices()` — the same 9 curated ratios/indices, kept in exact sync with that module rather than the \\~50-ratio set `4_apply_to_NW.R` used.\n\nWritten as a function so the identical computation can be applied to the training data in the applicability checks below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nadd_spectral_indices <- function(df) {\n  df %>%\n  mutate(BR = blue_corr7 / red_corr7,\n         BG = blue_corr7 / green_corr7,\n         NR = nir_corr7 / red_corr7,\n         GR = green_corr7 / red_corr7,\n         fai = nir_corr7 - (red_corr7 + (swir1_corr7 - red_corr7) * ((830 - 660) / (1650 - 660))),\n         NDVI = (nir_corr7 - red_corr7) / (nir_corr7 + red_corr7),\n         NDSSI = (blue_corr7 - nir_corr7) / (blue_corr7 + nir_corr7),\n         NDWI = (green_corr7 - nir_corr7) / (green_corr7 + nir_corr7),    # McFeeters 1996\n         MNDWI = (green_corr7 - swir1_corr7) / (green_corr7 + swir1_corr7)) %>%  # Xu 2006\n  mutate(across(c(BR, BG, NR, GR, fai, NDVI, NDSSI, NDWI, MNDWI),\n                ~ if_else(is.finite(.x), .x, NA_real_)))\n}\n\nNW_RS_ml <- add_spectral_indices(NW_RS_corr)\n\nlog(\"%s rows, %s unique sites after band correction + spectral indices\", nrow(NW_RS_ml), n_distinct(NW_RS_ml$r_id))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[14:28:45]  128078 rows, 397 unique sites after band correction + spectral indices \n```\n\n\n:::\n:::\n\n\n## Site characteristics and `shore_flag`\n\nElevation is straightforward (AWS terrain tiles, same as `02b_pull_site_characteristics.Rmd`). Catchment characteristics need an NHDPlusV2 `comid` to join into LakeCat — this file's own `comid` and `permanent_identifier` columns were both tested directly against the live LakeCat API and neither resolved (0/40 in a spot check; a raw API call against one `permanent_identifier` value returned an explicit 404), so every site is re-matched to its NHDPlusV2 waterbody polygon here via `nhdplusTools::get_waterbodies()` — a single bulk fetch over the full site extent, then a local nearest-feature spatial join, mirroring `01_filter_AquaMatch_Data.Rmd`'s own \"fetch once regionally, join locally\" pattern rather than one API call per site.\n\nThe same resolved polygon geometry gives `shore_flag` for free: `dist_to_wb` (0 if the site point falls inside its matched waterbody, otherwise the distance to it) and `dist_to_shore` (distance to the polygon's boundary specifically) are both computed directly, and combined the same way the training-time flag was defined (`shore_flag = 1` if the site is outside its matched waterbody **or** within 230 m of its shoreline).\n\nThis block, and the gridMET weather pull below, are the slowest part of the notebook and cache their results to `OUT_DIR` (elevation/waterbody/LakeCat → `NW_CLP_site_characteristics.feather`; weather → `NW_CLP_weather_raw.feather` / `NW_CLP_weather_summaries.feather`). A re-run loads straight from cache; set `FORCE_REFRESH_CACHE <- TRUE` in the setup chunk (e.g. after the input site set changes) to force a fresh fetch.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsite_char_cache <- file.path(OUT_DIR, \"NW_CLP_site_characteristics.feather\")\n\nif (!FORCE_REFRESH_CACHE && file.exists(site_char_cache)) {\n  sites_unique <- read_feather(site_char_cache)\n  log(\"loaded cached site characteristics (%s): %s sites\", site_char_cache, nrow(sites_unique))\n} else {\n  sites_unique <- NW_RS_ml %>% distinct(r_id, lat, lon)\n  log(\"n unique sites: %s\", nrow(sites_unique))\n\n  pts_sf <- st_as_sf(sites_unique, coords = c(\"lon\", \"lat\"), crs = 4326, remove = FALSE)\n\n  t0 <- Sys.time()\n  elev <- get_elev_point(pts_sf, src = \"aws\", z = 9)\n  log(\"elevation fetch took %.1f min\", as.numeric(difftime(Sys.time(), t0, units = \"mins\")))\n  elev_df <- st_drop_geometry(elev) %>% select(r_id, elevation_m = elevation)\n  sites_unique <- sites_unique %>% left_join(elev_df, by = \"r_id\")\n\n  # fresh NHDPlusV2 waterbody match: one bulk fetch over the full site extent,\n  # then a local nearest-feature join per site\n  aoi <- st_convex_hull(st_union(pts_sf)) %>% st_buffer(0.01)\n  t0 <- Sys.time()\n  waterbodies <- get_waterbodies(AOI = aoi)\n  log(\"waterbody fetch took %.1f s, %s polygons over the site extent\",\n      as.numeric(difftime(Sys.time(), t0, units = \"secs\")), nrow(waterbodies))\n\n  nearest_idx <- st_nearest_feature(pts_sf, waterbodies)\n  matched_wb <- waterbodies[nearest_idx, ]\n  dist_to_wb <- as.numeric(st_distance(pts_sf, matched_wb, by_element = TRUE))\n  dist_to_shore <- as.numeric(st_distance(pts_sf, st_boundary(matched_wb), by_element = TRUE))\n\n  sites_unique <- sites_unique %>%\n    mutate(comid = as.character(matched_wb$comid),\n           dist_to_wb = dist_to_wb, dist_to_shore = dist_to_shore,\n           shore_flag = as.numeric(dist_to_wb > 0 | dist_to_shore < 230))\n  log(\"shore_flag distribution:\"); print(table(sites_unique$shore_flag))\n\n  lakecat_metrics <- paste(c(\n    \"pctimp2006\", \"pcturbhi2006\", \"pcturblo2006\", \"pcturbmd2006\", \"pcturbop2006\",\n    \"pctconif2006\", \"pctdecid2006\", \"pctmxfst2006\",\n    \"pcthbwet2006\", \"pctwdwet2006\", \"pctcrop2006\"\n  ), collapse = \",\")\n\n  comids <- unique(na.omit(sites_unique$comid))\n  chunk_size <- 200\n  chunks <- split(comids, ceiling(seq_along(comids) / chunk_size))\n  # a chunk where NONE of its comids are LakeCat-covered throws rather than\n  # returning empty (seen directly while developing this notebook) - catch\n  # that per chunk so one bad chunk doesn't abort the whole fetch\n  lakecat_raw <- purrr::map_dfr(chunks, function(ch) {\n    tryCatch(lc_get_data(comid = paste(ch, collapse = \",\"), metric = lakecat_metrics,\n                         aoi = \"catchment\", showAreaSqKm = TRUE),\n             error = function(e) { log(\"LakeCat chunk failed (0 covered): %s\", conditionMessage(e)); tibble() })\n  })\n  log(\"LakeCat rows returned: %s / %s comids requested\", nrow(lakecat_raw), length(comids))\n\n  lakecat <- lakecat_raw %>%\n    mutate(comid = as.character(comid),\n           pct_forest_2006 = pctconif2006cat + pctdecid2006cat + pctmxfst2006cat,\n           pct_wetland_2006 = pcthbwet2006cat + pctwdwet2006cat,\n           pct_urban_2006 = pcturbhi2006cat + pcturblo2006cat + pcturbmd2006cat + pcturbop2006cat) %>%\n    select(comid, catchment_area_sqkm = catareasqkm,\n           pct_impervious_2006 = pctimp2006cat, pct_urban_2006, pct_forest_2006,\n           pct_cropland_2006 = pctcrop2006cat, pct_wetland_2006)\n\n  sites_unique <- sites_unique %>% left_join(lakecat, by = \"comid\")\n  log(\"sites with LakeCat data: %s / %s\", sum(!is.na(sites_unique$pct_impervious_2006)), nrow(sites_unique))\n\n  write_feather(sites_unique, site_char_cache)\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[14:28:45]  loaded cached site characteristics (NW_CLP_application/output/NW_CLP_site_characteristics.feather): 408 sites \n```\n\n\n:::\n:::\n\n\n## Antecedent weather\n\nSame gridMET fetch + rolling-window summary as `02c_pull_weather_summaries.Rmd`, run fresh for the NW/CLP sites — anchored on the image date alone (see the note at the top of this notebook).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nMAX_WINDOW_DAYS <- 30\nWINDOWS <- c(1, 3, 7, 30)\nVARS <- c(\"pr\", \"tmmx\", \"tmmn\", \"srad\")\nN_WORKERS <- 8\n\nweather_summary_cache <- file.path(OUT_DIR, \"NW_CLP_weather_summaries.feather\")\nweather_raw_cache <- file.path(OUT_DIR, \"NW_CLP_weather_raw.feather\")\n\nif (!FORCE_REFRESH_CACHE && file.exists(weather_summary_cache)) {\n  log(\"weather summaries cache found (%s), skipping gridMET fetch\", weather_summary_cache)\n} else if (!FORCE_REFRESH_CACHE && file.exists(weather_raw_cache)) {\n  weather_raw <- read_feather(weather_raw_cache)\n  log(\"loaded cached raw weather (%s): %s rows, skipping gridMET fetch\", weather_raw_cache, nrow(weather_raw))\n} else {\n  site_ranges <- NW_RS_ml %>%\n    group_by(r_id, lat, lon) %>%\n    summarize(min_date = min(date) - (MAX_WINDOW_DAYS + 5), max_date = max(date), .groups = \"drop\")\n  log(\"fetching gridMET for %s sites\", nrow(site_ranges))\n\n  fetch_one <- function(i, site_ranges) {\n    row <- site_ranges[i, ]\n    fetch <- function() {\n      pt <- sf::st_as_sf(data.frame(lon = row$lon, lat = row$lat), coords = c(\"lon\", \"lat\"), crs = 4326)\n      res <- getGridMET(AOI = pt, varname = VARS,\n                         startDate = as.character(row$min_date), endDate = as.character(row$max_date))\n      res$r_id <- row$r_id\n      res\n    }\n    tryCatch(fetch(), error = function(e) {\n      Sys.sleep(2)\n      tryCatch(fetch(), error = function(e2) data.frame(r_id = row$r_id, error = conditionMessage(e2)))\n    })\n  }\n\n  t0 <- Sys.time()\n  cl <- makeCluster(N_WORKERS, type = \"PSOCK\")\n  clusterEvalQ(cl, { suppressMessages(library(climateR)); suppressMessages(library(sf)) })\n  clusterExport(cl, c(\"site_ranges\", \"VARS\", \"fetch_one\"))\n  results <- parLapply(cl, seq_len(nrow(site_ranges)), fetch_one, site_ranges = site_ranges)\n  stopCluster(cl)\n  log(\"fetch took %.1f min\", as.numeric(difftime(Sys.time(), t0, units = \"mins\")))\n\n  ok <- Filter(function(x) !\"error\" %in% names(x), results)\n  failed <- Filter(function(x) \"error\" %in% names(x), results)\n  log(\"succeeded: %s sites, failed: %s sites\", length(ok), length(failed))\n  if (length(failed) > 0) {\n    write_csv(bind_rows(failed), file.path(OUT_DIR, \"NW_CLP_weather_fetch_failures.csv\"))\n  }\n\n  weather_raw <- bind_rows(ok)\n  write_feather(weather_raw, weather_raw_cache)\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[14:28:45]  weather summaries cache found (NW_CLP_application/output/NW_CLP_weather_summaries.feather), skipping gridMET fetch \n```\n\n\n:::\n:::\n\n\nSummarize the daily weather into the same 1/3/7/30-day rolling antecedent\nfeatures used in training, with each window ending the day before the\nimage date. The summaries are cached.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif (!FORCE_REFRESH_CACHE && file.exists(weather_summary_cache)) {\n  weather_summaries <- as.data.table(read_feather(weather_summary_cache))\n  log(\"loaded cached weather summaries (%s): %s rows, %s cols\",\n      weather_summary_cache, nrow(weather_summaries), ncol(weather_summaries))\n} else {\n  weather <- weather_raw %>%\n    mutate(date = as.Date(date),\n           precip_mm = pr, tmax_degC = tmmx - 273.15, tmin_degC = tmmn - 273.15,\n           tmean_degC = (tmax_degC + tmin_degC) / 2, srad_Wm2 = srad) %>%\n    select(r_id, date, precip_mm, tmax_degC, tmin_degC, tmean_degC, srad_Wm2)\n\n  setDT(weather)\n  setorder(weather, r_id, date)\n  site_splits <- split(weather, by = \"r_id\", keep.by = TRUE)\n\n  make_summary_one_site <- function(df) {\n    site_id <- df$r_id[1]\n    full_days <- data.table(date = seq(min(df$date), max(df$date), by = \"1 day\"))\n    df <- merge(full_days, df[, -\"r_id\"], by = \"date\", all.x = TRUE)\n    df[, r_id := site_id]\n    for (w in WINDOWS) {\n      df[[paste0(\"precip_mm_prev\", w)]] <- frollsum(df$precip_mm, n = w)\n      df[[paste0(\"tmax_degC_prev\", w)]] <- frollapply(df$tmax_degC, N = w, FUN = max)\n      df[[paste0(\"tmean_degC_prev\", w)]] <- frollmean(df$tmean_degC, n = w)\n      df[[paste0(\"tmin_degC_prev\", w)]] <- frollapply(df$tmin_degC, N = w, FUN = min)\n      df[[paste0(\"srad_Wm2_prev\", w)]] <- frollmean(df$srad_Wm2, n = w)\n    }\n    df[, date := date + 1]  # window on `date` covers the w days strictly BEFORE date\n    df\n  }\n\n  # frollapply() (used for the rolling max/min above) forks worker processes via\n  # parallel::mcparallel() whenever data.table has >1 thread available - Positron\n  # disallows forking the R session, so force single-threaded (non-forking) here\n  old_dt_threads <- getDTthreads()\n  setDTthreads(1)\n  t0 <- Sys.time()\n  weather_summaries <- rbindlist(lapply(site_splits, make_summary_one_site), fill = TRUE)\n  setDTthreads(old_dt_threads)\n  weather_summaries <- weather_summaries[!is.na(r_id)]\n  log(\"weather summaries took %.1f min: %s rows, %s cols\",\n      as.numeric(difftime(Sys.time(), t0, units = \"mins\")), nrow(weather_summaries), ncol(weather_summaries))\n  write_feather(as.data.frame(weather_summaries), weather_summary_cache)\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[14:28:47]  loaded cached weather summaries (NW_CLP_application/output/NW_CLP_weather_summaries.feather): 5151692 rows, 27 cols \n```\n\n\n:::\n:::\n\n\n## Assemble the model input table\n\nJoins bands/indices + site characteristics (including the freshly-computed `shore_flag`) + weather.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_input <- NW_RS_ml %>%\n  left_join(sites_unique %>% select(-lat, -lon, -comid), by = \"r_id\") %>%\n  left_join(as.data.frame(weather_summaries), by = c(\"r_id\", \"date\")) %>%\n  as.data.frame()  # weather_summaries carries a data.table class through the join otherwise,\n                    # which breaks plain `df[, feats]` column selection below\n\nlog(\"model input: %s rows, %s cols\", nrow(model_input), ncol(model_input))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[14:28:48]  model input: 128078 rows, 270 cols \n```\n\n\n:::\n\n```{.r .cell-code}\nlog(\"rows missing weather: %s / %s\", sum(is.na(model_input$precip_mm_prev30)), nrow(model_input))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[14:28:48]  rows missing weather: 0 / 128078 \n```\n\n\n:::\n\n```{.r .cell-code}\nlog(\"rows missing LakeCat catchment data: %s / %s\", sum(is.na(model_input$pct_impervious_2006)), nrow(model_input))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[14:28:48]  rows missing LakeCat catchment data: 0 / 128078 \n```\n\n\n:::\n\n```{.r .cell-code}\n# training now applies python/features.py's coarsen_site_features() -\n# catchment_area_sqkm winsorized at the training data's 99th percentile\n# (617.1 km2) then log-scale binned, pct_*_2006 land-cover fractions rounded\n# to the nearest percentage point - to keep a heavily-resampled or\n# catchment-outlier waterbody's static per-comid LakeCat values from acting\n# as a de facto waterbody ID a tree can key a memorized SDD value off of.\n# The winsorization cap is a fixed constant fit once on the training\n# distribution (see features.py's CATCHMENT_WINSORIZE_CAP_SQKM docstring),\n# not recomputed here, so any NW/CLP reservoir above it gets pulled down to\n# the same capped value production training used - the trained models\n# expect that same resolution at inference time, so it's replicated here\n# rather than passing full-precision LakeCat values into a model that never\n# saw them\nCATCHMENT_WINSORIZE_CAP_SQKM <- 617.1\n\n# same form as 07_regional_application.Rmd, which also applies it to the\n# training reference for the applicability checks\ncoarsen_site_features <- function(df) {\n  df %>%\n    mutate(catchment_area_sqkm = if_else(catchment_area_sqkm > 0,\n                                         10^round(log10(pmin(catchment_area_sqkm, CATCHMENT_WINSORIZE_CAP_SQKM)), 1),\n                                         catchment_area_sqkm),\n           across(c(pct_impervious_2006, pct_urban_2006, pct_forest_2006,\n                    pct_cropland_2006, pct_wetland_2006), ~ round(.x, 0)))\n}\n\nmodel_input <- coarsen_site_features(model_input)\n```\n:::\n\n\n## Load the 10-seed XGBoost ensemble and predict\n\nEach seed's own final feature set and fold models (`xg_models/v3_production/seed{601-610}/`) are used as trained — no re-selection, no re-tuning. Every QA'd scene receives a prediction. Scenes with missing inputs (for example, weather for a site whose gridMET fetch failed) are still predicted, using XGBoost's native handling of `NA`, but they fail the completeness check below and are excluded from evaluation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nseed_preds <- vector(\"list\", length(ENSEMBLE_SEEDS))\n\nfor (i in seq_along(ENSEMBLE_SEEDS)) {\n  seed <- ENSEMBLE_SEEDS[i]\n  seed_dir <- file.path(MODEL_DIR, paste0(\"seed\", seed))\n  feats <- fromJSON(file.path(seed_dir, \"final_tune_xgboost.json\"))$features\n\n  missing_cols <- setdiff(feats, names(model_input))\n  stopifnot(\"model input is missing columns this seed's model needs\" = length(missing_cols) == 0)\n\n  X <- as.matrix(model_input[, feats])\n  fold_preds <- matrix(NA_real_, nrow = nrow(X), ncol = 4)\n  for (fold in 1:4) {\n    booster <- xgb.load(file.path(seed_dir, paste0(\"xgboost_fold\", fold, \".json\")))\n    fold_preds[, fold] <- predict(booster, X)\n  }\n  seed_preds[[i]] <- rowMeans(fold_preds)\n  log(\"seed%s: predicted (%s features)\", seed, length(feats))\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[14:28:54]  seed601: predicted (26 features) \n[14:28:58]  seed602: predicted (26 features) \n[14:29:00]  seed603: predicted (33 features) \n[14:29:05]  seed604: predicted (29 features) \n[14:29:10]  seed605: predicted (26 features) \n[14:29:14]  seed606: predicted (28 features) \n[14:29:20]  seed607: predicted (28 features) \n[14:29:24]  seed608: predicted (29 features) \n[14:29:27]  seed609: predicted (30 features) \n[14:29:31]  seed610: predicted (33 features) \n```\n\n\n:::\n\n```{.r .cell-code}\nmodel_input$pred_sdd <- rowMeans(do.call(cbind, seed_preds))\nlog(\"prediction summary:\"); print(summary(model_input$pred_sdd))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[14:29:31]  prediction summary: \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n-0.5152  0.8891  1.4752  1.8378  2.5439  8.4902 \n```\n\n\n:::\n:::\n\n\n## Applicability checks\n\nThese are the same checks `07_regional_application.Rmd` applies before counting an estimate. Each is computed against the same training reference, using the same definitions:\n\n1. the scene comes from a Landsat mission represented in training;\n2. it falls within the seasonal window of the training matchups (the central 98% of their day of year);\n3. every model input is available;\n4. every model input falls within the training range;\n5. the scene falls inside the area of applicability (AOA; Meyer & Pebesma 2021);\n6. the estimate is no shallower than the shallowest SDD in the training data.\n\nSee `07` for the rationale behind each check. Because the reference, the features, and the threshold rule are shared, the seasonal window and AOA threshold computed here match `07`'s `aoa_parameters.json`, and the chunk below checks this when that file exists.\n\n### Training reference\n\nThe reference is the cross-validation pool that trained the ensemble (every non-holdout row of `base_with_splits.parquet`), engineered with the same functions applied to the NW/CLP data above.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nTRAINING_MISSIONS <- c(\"LT04\", \"LT05\", \"LE07\", \"LC08\", \"LC09\")\n\nmodel_feats <- map(ENSEMBLE_SEEDS, \\(s) {\n  fromJSON(file.path(MODEL_DIR, paste0(\"seed\", s), \"final_tune_xgboost.json\"))$features\n}) %>%\n  unlist() %>%\n  unique() %>%\n  sort()\n\ntrain_pool <- read_parquet(TRAINING_PATH) %>%\n  filter(!is_holdout) %>%\n  mutate(date = as.Date(date)) %>%\n  add_spectral_indices() %>%\n  coarsen_site_features()\nlog(\"training reference: %s CV-pool rows\", nrow(train_pool))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[14:29:31]  training reference: 8937 CV-pool rows \n```\n\n\n:::\n:::\n\n\n### Training range, seasonal window, and completeness\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfeature_ranges <- train_pool %>%\n  summarise(across(all_of(model_feats), list(min = ~ min(.x, na.rm = TRUE), max = ~ max(.x, na.rm = TRUE)))) %>%\n  pivot_longer(everything(), names_to = c(\"feature\", \".value\"), names_pattern = \"(.*)_(min|max)$\")\n\nin_range <- function(df) {\n  ok <- rep(TRUE, nrow(df))\n  for (i in seq_len(nrow(feature_ranges))) {\n    x <- df[[feature_ranges$feature[i]]]\n    ok <- ok & !is.na(x) & x >= feature_ranges$min[i] & x <= feature_ranges$max[i]\n  }\n  ok\n}\n\nfeature_complete <- function(df) complete.cases(df[, model_feats])\n\nseason_window <- round(quantile(yday(train_pool$date), c(0.01, 0.99)))\nin_season <- function(df) between(yday(df$date), season_window[1], season_window[2])\nlog(\"seasonal window: day of year %s-%s\", season_window[1], season_window[2])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[14:29:31]  seasonal window: day of year 70-320 \n```\n\n\n:::\n:::\n\n\n### Area of applicability\n\nThe dissimilarity index (DI) is calculated in the SHAP-weighted, standardized feature space of the unanimous-core features. The threshold is the upper whisker of the training pool's cross-fold nearest-neighbor DI.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshap_weights <- read_csv(file.path(MODEL_DIR, \"ensemble_mean_abs_shap.csv\"), show_col_types = FALSE)\naoa_feats <- shap_weights$feature\nstopifnot(all(aoa_feats %in% model_feats))\n\ncenters <- map_dbl(aoa_feats, \\(f) mean(train_pool[[f]], na.rm = TRUE))\nscales <- map_dbl(aoa_feats, \\(f) sd(train_pool[[f]], na.rm = TRUE))\nweights <- shap_weights$mean_abs_shap\n\nto_aoa_space <- function(df) {\n  X <- as.matrix(df[, aoa_feats])\n  X <- sweep(sweep(X, 2, centers), 2, scales, \"/\")\n  sweep(X, 2, weights, \"*\")\n}\n\ntrain_X <- to_aoa_space(train_pool)\ntrain_complete <- complete.cases(train_X)\ntrain_X <- train_X[train_complete, ]\nd_bar <- mean(dist(train_X))\n\ntrain_fold <- train_pool$holdout_part[train_complete]\ntrain_di <- numeric(nrow(train_X))\nfor (k in unique(train_fold)) {\n  in_k <- train_fold == k\n  train_di[in_k] <- nn2(train_X[!in_k, ], train_X[in_k, ], k = 1)$nn.dists[, 1] / d_bar\n}\naoa_threshold <- boxplot.stats(train_di)$stats[5]\n\ncompute_di <- function(df) {\n  di <- rep(NA_real_, nrow(df))\n  X <- to_aoa_space(df)\n  ok <- complete.cases(X)\n  di[ok] <- nn2(train_X, X[ok, , drop = FALSE], k = 1)$nn.dists[, 1] / d_bar\n  di\n}\nlog(\"AOA threshold (DI): %.3f\", aoa_threshold)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[14:29:32]  AOA threshold (DI): 0.385 \n```\n\n\n:::\n\n```{.r .cell-code}\n# consistency with the regional application, when its outputs are on hand\nregional_aoa_path <- \"regional_clarity/aquamatch_files/application/aoa_parameters.json\"\nif (file.exists(regional_aoa_path)) {\n  regional_aoa <- fromJSON(regional_aoa_path)\n  stopifnot(\"AOA threshold differs from 07_regional_application.Rmd\" =\n              isTRUE(all.equal(aoa_threshold, regional_aoa$aoa_threshold)),\n            \"seasonal window differs from 07_regional_application.Rmd\" =\n              all(unname(season_window) == regional_aoa$season_window_doy))\n}\n```\n:::\n\n\n### Apply the checks\n\nEach check builds on the previous one. The table counts scenes (rows) and sites remaining after each step. It begins with the siteSR QA steps above, so it reads as one continuous filtering record.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmission_code <- c(LANDSAT_4 = \"LT04\", LANDSAT_5 = \"LT05\", LANDSAT_7 = \"LE07\",\n                  LANDSAT_8 = \"LC08\", LANDSAT_9 = \"LC09\")\n\nmodel_input <- model_input %>%\n  mutate(mission_code = unname(mission_code[mission]),\n         pass_mission = mission_code %in% TRAINING_MISSIONS,\n         pass_season = pass_mission & in_season(.),\n         pass_complete = pass_season & feature_complete(.),\n         pass_range = pass_complete & in_range(.),\n         di = compute_di(.),\n         pass_aoa = pass_range & !is.na(di) & di <= aoa_threshold,\n         pass_plausible = pass_aoa & pred_sdd >= min(train_pool$harmonized_value))\n\nfilter_steps <- qa_log %>%\n  bind_rows(tibble(\n    step = c(\"Landsat mission represented in training\",\n             \"Within seasonal window of training matchups\",\n             \"All model inputs available\",\n             \"Within training range of every input\",\n             \"Inside area of applicability\",\n             \"Estimate no shallower than training minimum\"),\n    n_rows = map_int(c(\"pass_mission\", \"pass_season\", \"pass_complete\", \"pass_range\", \"pass_aoa\", \"pass_plausible\"),\n                     \\(col) sum(model_input[[col]])),\n    n_sites = map_int(c(\"pass_mission\", \"pass_season\", \"pass_complete\", \"pass_range\", \"pass_aoa\", \"pass_plausible\"),\n                      \\(col) n_distinct(model_input$r_id[model_input[[col]]]))\n  ))\nfilter_steps\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 11 × 3\n   step                                             n_rows n_sites\n   <chr>                                             <int>   <int>\n 1 Raw NW/CLP siteSR rows                           321637     485\n 2 Pixel QA (DSWE share/count, no clouds in buffer) 188031     408\n 3 Median surface temperature 0-40 °C               183983     406\n 4 Scene cloud cover < 20%                          133275     397\n 5 Band RANSAC                                      128078     397\n 6 Landsat mission represented in training          128078     397\n 7 Within seasonal window of training matchups      117129     395\n 8 All model inputs available                       117129     395\n 9 Within training range of every input              91536     303\n10 Inside area of applicability                      85030     301\n11 Estimate no shallower than training minimum       84495     301\n```\n\n\n:::\n:::\n\n\n## Match to observed Secchi depth\n\nSame GNIS-name harmonization `4_apply_to_NW.R` used (a handful of names differ between the water-quality record's `feature` and this RS file's NHD-derived `gnis_name`).\n\nMatched with the same ±5-day window `02a_make_matches.Rmd` uses for the regional training data, rather than requiring an exact same-day match — an exact-date join silently drops any in-situ observation that doesn't happen to fall on a satellite overpass date, which is most of them, and undercounts the evaluable pairs relative to every other evaluation in this project. Unlike training (where the same image legitimately pairs with more than one nearby SDD measurement as separate rows), evaluation de-duplicates by **image**, not by observation: each unique overpass keeps only the single SDD measurement closest in time to it, so a dense field-sampling week landing inside one overpass's window doesn't score that one static prediction against several different observed values as if it were several independent tests of the model. `time_diff` (predicted image date minus observed sample date, in days) is kept for the same match-quality check `05_evaluate_ensemble.ipynb` runs on the regional holdout.\n\nOnly scenes that pass every applicability check are matched for the primary evaluation. The same matching is also run on every QA'd scene, with the applicability checks ignored, so the effect of the checks on the reported performance can be seen directly (see the metrics below). Matching is therefore written as a function, `match_to_observed()`.\n\nCandidate pairs are also screened for a heavy single-day rain event between the image date and the field date, the same screen `02a_make_matches.Rmd` applies to the regional training matchups, so the out-of-sample evaluation is held to the same bar as training. Screening happens on **candidates**, before the closest-in-time selection above, not after: a heavy rain event during an observation's single nearest candidate image would otherwise drop that observation outright even when a perfectly good, only slightly-further-away, uncontaminated image is also available in the window. Direction-agnostic (checked over `[min(image date, field date), max(image date, field date)]`), matching the original filter.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nMATCH_WINDOW_DAYS <- 5\nHEAVY_RAIN_MM <- 25.4  # NOAA/EPA \"heavy precipitation day\" threshold (1 inch/24hr)\n\nNW_sdd <- read_csv(SDD_PATH, show_col_types = FALSE) %>%\n  mutate(gnis_name = case_when(feature == \"Carter Lake\" ~ \"Carter Lake Reservoir\",\n                               feature == \"Shadow Mountain Reservoir\" ~ \"Shadow Mountain Lake\",\n                               feature == \"Granby Reservoir\" ~ \"Lake Granby\",\n                               TRUE ~ feature))\n\nres_names <- unique(NW_sdd$gnis_name)\nlog(\"%s reservoirs with observed SDD: %s\", length(res_names), paste(res_names, collapse = \", \"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[14:29:34]  8 reservoirs with observed SDD: Shadow Mountain Lake, Grand Lake, Carter Lake Reservoir, Lake Granby, Horsetooth Reservoir, Willow Creek Reservoir, Windy Gap Reservoir, Columbine Lake \n```\n\n\n:::\n\n```{.r .cell-code}\n# raw daily gridMET precip isn't kept in scope once weather_summaries loads\n# from cache (see weather-fetch above), so read it back explicitly here\nweather_raw_rain <- read_feather(weather_raw_cache) %>% mutate(date = as.Date(date))\nsite_res_lookup <- model_input %>% distinct(r_id, gnis_name)\nweather_raw_res <- weather_raw_rain %>%\n  inner_join(site_res_lookup, by = \"r_id\") %>%\n  select(gnis_name, date, pr)\n\nmatch_to_observed <- function(preds) {\n  pred_at_obs_res <- preds %>%\n    filter(gnis_name %in% res_names) %>%\n    summarise(predicted = mean(pred_sdd), .by = c(date, gnis_name)) %>%\n    rename(date_pred = date)\n\n  obs_at_res <- NW_sdd %>%\n    summarise(observed = mean(value), .by = c(date, gnis_name)) %>%\n    rename(date_obs = date)\n\n  # every (obs, pred) candidate pair per reservoir within the window\n  candidates <- obs_at_res %>%\n    # every observation pairs with every image at its reservoir before the\n    # window filter, so many-to-many is expected here\n    inner_join(pred_at_obs_res, by = \"gnis_name\", relationship = \"many-to-many\") %>%\n    mutate(time_diff = as.numeric(date_pred - date_obs)) %>%\n    filter(abs(time_diff) <= MATCH_WINDOW_DAYS)\n\n  # peak single-day precip at ANY site in the reservoir, strictly between the\n  # earlier and later of the image date and the field date - a data.table\n  # non-equi (interval) join, the same approach 02a_make_matches.Rmd\n  # uses at the individual-site level in the regional pipeline\n  candidates <- candidates %>%\n    mutate(gap_start = pmin(date_obs, date_pred), gap_end = pmax(date_obs, date_pred),\n           cand_id = row_number())\n\n  candidates_dt <- as.data.table(candidates)\n  wx_dt <- as.data.table(weather_raw_res)\n  setkey(wx_dt, gnis_name, date)\n\n  joined <- wx_dt[candidates_dt, on = .(gnis_name, date > gap_start, date <= gap_end),\n                  nomatch = NA, allow.cartesian = TRUE]\n  gap_max <- joined[, .(gap_max_precip_mm = max(pr, na.rm = TRUE)), by = cand_id]\n  gap_max[!is.finite(gap_max_precip_mm), gap_max_precip_mm := 0]\n\n  candidates <- candidates %>%\n    left_join(as.data.frame(gap_max), by = \"cand_id\") %>%\n    mutate(gap_max_precip_mm = coalesce(gap_max_precip_mm, 0))\n\n  n_flagged <- sum(candidates$gap_max_precip_mm >= HEAVY_RAIN_MM)\n  log(\"%s / %s candidate (obs, image) pairs flagged for a heavy single-day rain event (>= %.1f mm) in their gap - excluded before closest-match selection\",\n      n_flagged, nrow(candidates), HEAVY_RAIN_MM)\n\n  candidates <- candidates %>%\n    filter(gap_max_precip_mm < HEAVY_RAIN_MM) %>%\n    select(-gap_start, -gap_end, -cand_id, -gap_max_precip_mm)\n\n  # only now, among the rain-screened candidates, keep the single SDD\n  # observation closest in time to each image - de-duplicating by observation\n  # instead would still let the same image be the nearest available match for\n  # several different field visits (e.g. a dense sampling week landing inside\n  # one overpass's window), which scores that one static prediction against\n  # each of those visits separately and counts it multiple times in the\n  # evaluation metrics. De-duplicating by image instead keeps each unique\n  # overpass contributing exactly one (prediction, observation) pair.\n  pred_obs <- candidates %>%\n    arrange(gnis_name, date_pred, abs(time_diff)) %>%\n    distinct(gnis_name, date_pred, .keep_all = TRUE) %>%\n    rename(date = date_obs) %>%\n    select(-date_pred)\n\n  n_obs_reused <- nrow(pred_obs) - n_distinct(pred_obs %>% select(gnis_name, date))\n  log(\"%s matched (image, reservoir) pairs within +/- %s days, one SDD measurement kept per image\",\n      nrow(pred_obs), MATCH_WINDOW_DAYS)\n  log(\"%s of those SDD measurements were the closest available observation for more than one image\",\n      n_obs_reused)\n  log(\"time_diff (pred image date - obs sample date): mean=%.2f, median=%.1f, range=[%s, %s] days\",\n      mean(pred_obs$time_diff), median(pred_obs$time_diff), min(pred_obs$time_diff), max(pred_obs$time_diff))\n  pred_obs\n}\n\npred_obs <- match_to_observed(filter(model_input, pass_plausible))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[14:29:36]  4 / 1305 candidate (obs, image) pairs flagged for a heavy single-day rain event (>= 25.4 mm) in their gap - excluded before closest-match selection \n[14:29:36]  730 matched (image, reservoir) pairs within +/- 5 days, one SDD measurement kept per image \n[14:29:36]  95 of those SDD measurements were the closest available observation for more than one image \n[14:29:36]  time_diff (pred image date - obs sample date): mean=0.15, median=0.0, range=[-5, 5] days \n```\n\n\n:::\n\n```{.r .cell-code}\nlog(\"-- comparison: same matching, applicability checks ignored --\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[14:29:36]  -- comparison: same matching, applicability checks ignored -- \n```\n\n\n:::\n\n```{.r .cell-code}\npred_obs_all_qa <- match_to_observed(model_input)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[14:29:36]  4 / 1330 candidate (obs, image) pairs flagged for a heavy single-day rain event (>= 25.4 mm) in their gap - excluded before closest-match selection \n[14:29:36]  754 matched (image, reservoir) pairs within +/- 5 days, one SDD measurement kept per image \n[14:29:36]  101 of those SDD measurements were the closest available observation for more than one image \n[14:29:36]  time_diff (pred image date - obs sample date): mean=0.14, median=0.0, range=[-5, 5] days \n```\n\n\n:::\n:::\n\n\nCheck whether the time gap within a matchup relates to prediction error. A\nstrong correlation would suggest that loosely timed pairs, rather than the\nmodel, are driving the error.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# same diagnostic 05_evaluate_ensemble.ipynb runs on the regional holdout: does\n# looser match-ups (larger |time_diff|) correlate with worse prediction error?\npred_obs <- pred_obs %>% mutate(abs_error = abs(predicted - observed))\ngap_corr <- cor(abs(pred_obs$time_diff), pred_obs$abs_error)\nlog(\"Pearson r(|time_diff|, abs_error) = %.3f (n=%s)\", gap_corr, nrow(pred_obs))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[14:29:36]  Pearson r(|time_diff|, abs_error) = 0.049 (n=730) \n```\n\n\n:::\n\n```{.r .cell-code}\nggplot(pred_obs, aes(x = time_diff, y = abs_error)) +\n  geom_point(size = 2, alpha = 0.6, color = ROSS_LT_PAL[1]) +\n  labs(x = \"time gap: predicted image date minus observed sample date (days)\",\n       y = \"absolute prediction error (m)\",\n       title = sprintf(\"match-up time gap vs. error (Pearson r=%.2f)\", gap_corr)) +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](Northern_Water_application_files/figure-html/match-quality-check-1.png){width=672}\n:::\n:::\n\n\n## Predicted vs. observed\n\nEnsemble estimates against observed Secchi depth for every matched image,\ncolored by reservoir. The grey line is 1:1.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npred_obs <- pred_obs |> \n  mutate(resid = predicted-observed)\nggplot(pred_obs, aes(x = observed, y = predicted, color = gnis_name)) +\n  geom_point(size = 2.5, alpha = 0.8) +\n  geom_abline(slope = 1, intercept = 0, color = \"grey40\") +\n  scale_x_continuous(limits = c(0, NA)) +\n  scale_y_continuous(limits = c(0, NA)) +\n  scale_color_manual(values = ROSS_LT_PAL) +\n  labs(x = \"observed Secchi depth (m)\", y = \"predicted Secchi depth (m)\", color = NULL) +\n  theme_bw() +\n  theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![](Northern_Water_application_files/figure-html/pred-obs-plot-1.png){width=672}\n:::\n:::\n\n\nCompute error metrics across all matched observations: RMSE, MAE, MAPE,\nbias, percent bias, sMAPE, R², and n. Then compute RMSE, bias, R², and n\nfor each reservoir, sorted from worst to best RMSE. Finally, compare the\nprimary evaluation with the same matching run on every QA'd scene,\nignoring the applicability checks.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nevals_NW <- pred_obs %>%\n  summarise(rmse = rmse(observed, predicted),\n            mae = mae(observed, predicted),\n            mape = mape(observed, predicted),\n            bias = bias(observed, predicted),\n            p.bias = percent_bias(observed, predicted),\n            smape = smape(observed, predicted),\n            r2 = cor(observed, predicted)^2,\n            n = n())\nevals_NW\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 8\n   rmse   mae  mape   bias p.bias smape    r2     n\n  <dbl> <dbl> <dbl>  <dbl>  <dbl> <dbl> <dbl> <int>\n1  1.11 0.845 0.552 -0.274 -0.407 0.254 0.387   730\n```\n\n\n:::\n\n```{.r .cell-code}\nevals_NW_by_res <- pred_obs %>%\n  summarise(rmse = rmse(observed, predicted), bias = bias(observed, predicted),\n            r2 = cor(observed, predicted)^2, n = n(),\n            .by = gnis_name) %>%\n  arrange(desc(rmse))\nevals_NW_by_res\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 7 × 5\n  gnis_name               rmse   bias    r2     n\n  <chr>                  <dbl>  <dbl> <dbl> <int>\n1 Windy Gap Reservoir    1.96  -1.53  0.213    15\n2 Lake Granby            1.28  -0.547 0.304    99\n3 Carter Lake Reservoir  1.26   0.227 0.356   131\n4 Shadow Mountain Lake   1.14  -0.815 0.309   156\n5 Grand Lake             1.03  -0.447 0.392   140\n6 Willow Creek Reservoir 0.911  0.128 0.602    38\n7 Horsetooth Reservoir   0.731  0.215 0.380   151\n```\n\n\n:::\n\n```{.r .cell-code}\nevals_NW_checks <- bind_rows(\n  pred_obs %>% mutate(scenes = \"passes every applicability check\"),\n  pred_obs_all_qa %>% mutate(scenes = \"all QA'd scenes (checks ignored)\")\n) %>%\n  summarise(rmse = rmse(observed, predicted), mae = mae(observed, predicted),\n            bias = bias(observed, predicted), r2 = cor(observed, predicted)^2, n = n(),\n            .by = scenes)\nevals_NW_checks\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 6\n  scenes                            rmse   mae   bias    r2     n\n  <chr>                            <dbl> <dbl>  <dbl> <dbl> <int>\n1 passes every applicability check  1.11 0.845 -0.274 0.387   730\n2 all QA'd scenes (checks ignored)  1.10 0.845 -0.277 0.394   754\n```\n\n\n:::\n:::\n\n\n## Time series\n\nPredicted and observed Secchi depth through time for each reservoir from\n2008 onward. This shows whether the model follows seasonal and interannual\npatterns, in addition to matching individual values.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npred_obs %>%\nfilter(date > ymd(\"2008-01-01\")) %>%\n\n  pivot_longer(c(predicted, observed), names_to = \"source\", values_to = \"value\") %>%\n  ggplot(aes(x = date, y = value, color = source)) +\n  geom_point(size = 2, alpha = 0.6) +\n  facet_grid(gnis_name ~ ., scales = \"free_y\", labeller = label_wrap_gen(15)) +\n  scale_color_manual(values = ROSS_LT_PAL) +\n  labs(x = NULL, y = \"Secchi depth (m)\", color = NULL) +\n  theme_bw() +\n  theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![](Northern_Water_application_files/figure-html/timeseries-1.png){width=672}\n:::\n:::\n\n\n## Export\n\nWrite the matched predicted/observed pairs, the overall and per-reservoir\nmetrics, the comparison with and without the applicability checks, the\nstep-by-step filter counts, and the full prediction record for every QA'd\nNW/CLP image (including images with no matching field observation) with\neach image's pass/fail flags.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwrite_csv(pred_obs, file.path(OUT_DIR, \"NW_CLP_pred_obs.csv\"))\nwrite_csv(evals_NW, file.path(OUT_DIR, \"NW_CLP_eval_metrics.csv\"))\nwrite_csv(evals_NW_by_res, file.path(OUT_DIR, \"NW_CLP_eval_metrics_by_reservoir.csv\"))\nwrite_csv(evals_NW_checks, file.path(OUT_DIR, \"NW_CLP_eval_metrics_applicability.csv\"))\nwrite_csv(filter_steps, file.path(OUT_DIR, \"NW_CLP_filter_steps.csv\"))\n\n# full out-of-sample prediction record (not just the subset with a matched observation)\nwrite_feather(model_input %>% select(r_id, date, mission, gnis_name, comid, lat, lon, pred_sdd, di, starts_with(\"pass_\")),\n              file.path(OUT_DIR, \"NW_CLP_full_predictions.feather\"))\nlog(\"wrote outputs to %s/\", OUT_DIR)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[14:29:37]  wrote outputs to NW_CLP_application/output/ \n```\n\n\n:::\n:::\n\n\n## Summary\n\nNW/CLP was never part of the training, holdout, or CV data. Under the same siteSR QA and applicability checks as the regional application, the ensemble scores **RMSE 1.105 m, MAE 0.845 m, bias −0.274 m, R² 0.387** on this out-of-sample basin. The evaluation covers 730 matched (image, reservoir) pairs across 7 reservoirs. Pairs are matched within the same ±5-day window used for the regional training data and screened for heavy single-day rain between image and field dates. Each pair is de-duplicated by **image**, so every overpass contributes exactly one (prediction, observation) pair. The time gap within a pair does not correlate with error (r = 0.05), so match quality is not driving the result.\n\n**The filters shape which data are evaluated, not how well the model does on them.** The siteSR QA removes most of the record: 321,637 raw scene–site rows become 128,078. Pixel QA accounts for the largest cut (41%), followed by scene cloud cover, and band RANSAC removes a further 4%. The applicability checks then remove about a third of the QA'd scenes. Most of these fall outside the training range of at least one input, which excludes 92 of 397 sites entirely. Smaller cuts come from the seasonal window and the AOA. Matched scenes are almost all in-domain, however: only 24 of the 754 QA'd matched pairs fail an applicability check. Performance with and without the checks is effectively identical (RMSE 1.105 m vs. 1.103 m). The out-of-domain scenes are concentrated at sites and times without field data, which is where the checks matter most for any operational use of these estimates (see `NW_CLP_full_predictions.feather`, which carries every image's pass/fail flags).\n\n**The model underpredicts in NW/CLP, while it overpredicts on the regional holdout** (holdout RMSE 1.259 m, bias +0.148 m). The two errors run in opposite directions, so the transfer error here is a basin-specific shift, not a general calibration offset. Four reservoirs carry most of the underprediction: Shadow Mountain Lake (bias −0.82 m), Lake Granby (−0.55 m), Grand Lake (−0.45 m), and Windy Gap Reservoir (−1.53 m). Horsetooth Reservoir (+0.22 m), Carter Lake (+0.23 m), and Willow Creek Reservoir (+0.13 m) are close to unbiased.\n\n**Per-reservoir performance** (n = 15 to 156 matched pairs): Horsetooth Reservoir is the best performer (RMSE 0.73 m, n = 151). Windy Gap Reservoir is the worst (RMSE 1.96 m, R² 0.21, n = 15), though its sample is small. Willow Creek Reservoir has the highest R² (0.60, n = 38). Columbine Lake has field data but no scenes that match within the window after QA.\n\n**Data-pipeline notes:**\n\n- Site characteristics resolved for **all 408 sites** that pass pixel QA, via a fresh NHDPlusV2 spatial match. This file's own `comid`/`permanent_identifier` columns cannot be used with LakeCat.\n- `shore_flag` is 1 for 364 of 408 sites (89%), well above the training data's roughly 50/50 split. This is plausible for this site set, in which many points sit on smaller reservoirs or near shore, and is worth keeping in mind when interpreting predictions for these sites.\n- Scene cloud cover comes from AquaMatch's scene metadata, which covers 95% of this file's scenes. The remaining 5% cannot be confirmed as clear and are excluded, the same treatment the regional data receive.\n",
    "supporting": [
      "Northern_Water_application_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}